<#
check_rule_coverage.ps1 - AS.1's own coverage report.

"Which rules have no test-success; which have only one" - BETA_ROADMAP.md's
AS.1, scoped over several passes once a static scan of the hand-written
scripts/english.vla turned out to undercount the moment a generator
(TABLE-FAMILY) is involved: a generator's own CALL site is one line in that
file; the rule/test it expands to don't exist as text anywhere a scanner
could read them. G-EXPANDER (this file's own real prerequisite) closes that
gap by writing the fully macro-expanded form to a sibling artifact,
scripts/polyglotta/english_expanded.vla (beside its source) - every english-vla/test-success/test-fail/
defmacro/english-function directive, generated or hand-written, in
registration order. This script reads that artifact, never english.vla
itself, for the identical reason check_backend_parity.ps1 reads
VLA_HeadTable.bas's own AddRow calls rather than re-deriving the form
catalog by hand: the artifact and the real grammar can never silently
drift apart, because the artifact IS the grammar, made literal.

WHAT COUNTS AS ATTRIBUTION: positional, not semantic - a heuristic, stated
as plainly as AS.8's own head-position scan states itself. Walking the
artifact top-to-bottom, a test-success is attributed to the nearest
PRECEDING english-vla/english-vla-override form. This is evidence a human
or generator INTENDED that test to prove that rule, never proof the test
actually FIRED it - a rule can be shadowed by an earlier, more general
rule's own wildcard slot (F.4's own found instance, "show cell in column
...") and still show a positionally-attached test here, because the wrong
rule firing can still produce byte-identical output to what the test
expects. F.4 stays the owner of that failure mode (general, not
corpus-bound, shadowing detection); this script reports density, not
correctness. test-fail is counted at the file level only, never attributed
to a rule - english.vla's own five test-fail proofs sit in one dedicated
negative-proofs block, none positionally adjacent to the rule they'd need
to be attributed to (checked directly against the real corpus).

FORM-BOUNDARY SCAN: a line matching ^\(([A-Za-z][\w-]*) opens a new
top-level form of that head symbol; everything through the line before the
next such match is its body. Column-0-anchored, multi-line-tolerant by
design. The real artifact IS G-EXPANDER's pretty-printed rendering
(VLA_Lint.VlaLintFormat, GEXPANDERLINT.0): the head sits alone on its line
and the form's own arguments verticalize under it, so a rule's pattern
string is on the line AFTER "(english-vla", never the same one. The form
boundary scan never cared; the pattern extraction did - it read the head
line only, and printed "(pattern unreadable)" for every rule from the day
the artifact went vertical until 2026-09-07, hidden behind a staleness
gate that rarely let the script run to its report. It now reads ahead.
VLA_Lint.bas's own house style never indents a top-level form relative to
its siblings, so column-0 anchoring stays correct. A line matching
^;\s*row:\s*(.+)$ immediately above a form is captured as that form's
LISTOPS-PROVENANCE label when one exists.

Usage:  pwsh -File tools/check_rule_coverage.ps1 [-ArtifactPath <path>]
#>

param(
    [string]$ArtifactPath
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $ArtifactPath) {
    # The artifact is written BESIDE its source (EnglishIdeExportExpandedVocabulary
    # derives the name from the source path), so since EDITION-MANIFEST moved the
    # phrasebooks under scripts\polyglotta\ (2026-09-01) it lands there; the flat
    # scripts\ location is kept as a fallback for an artifact exported before the move.
    $ArtifactPath = Join-Path $repoRoot (Join-Path (Join-Path "scripts" "polyglotta") "english_expanded.vla")
    if (-not (Test-Path -LiteralPath $ArtifactPath)) { $ArtifactPath = Join-Path $repoRoot (Join-Path "scripts" "english_expanded.vla") }

}

if (-not (Test-Path -LiteralPath $ArtifactPath)) {
    Write-Error "No expanded artifact at $ArtifactPath - export one first (Frazaro ribbon: Export Expanded Vocabulary), or pass -ArtifactPath."
}

$lines = Get-Content -LiteralPath $ArtifactPath

# --- Staleness gate: refuse loudly rather than report on stale input --------
# G-EXPANDER's own header (EnglishExpandedVocabularyText, VLA_SentenceEngine.bas):
#   line 1: "; GENERATED by ... from <bare-filename> - ..."
#   line 2: "; source-hash: <8 hex> over <N> non-whitespace bytes - ..."   (0.5.1+)
#           "; source-size: <N> bytes - ..."                                (legacy)
#
# 0.5.1 (owner call, 2026-09-07): the stamp became a hash over the source's
# NON-WHITESPACE bytes. The byte size flagged every whitespace-only touch -
# a Lint VLA re-indent, a CRLF/LF checkout difference - as stale, and Beta's
# history holds at least four commits to the artifact that changed nothing
# but the stamp line. Whitespace between tokens never changes what the
# phrasebook means, so it must not change whether its export counts as
# current. A legacy source-size stamp is still honored (size comparison, as
# before) so an artifact exported before this change degrades to the old
# behaviour rather than erroring; the first re-export replaces it.
#
# Get-SourceHash is the byte-for-byte twin of VLA_SentenceEngine.bas's
# EnglishSourceHash: h = (h * 31 + b) mod 2^32 over every byte that is not
# tab/LF/CR/space, rendered as eight uppercase hex digits, plus the count of
# bytes that took part. Raw bytes on both sides, never decoded text, so a
# BOM or a non-ASCII character cannot make the two disagree. Change one
# side and you must change the other.
function Get-SourceHash([string]$path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    [uint64]$h = 0
    [long]$counted = 0
    foreach ($b in $bytes) {
        if ($b -ne 9 -and $b -ne 10 -and $b -ne 13 -and $b -ne 32) {
            $h = ($h * 31 + $b) % 4294967296
            $counted++
        }
    }
    return [pscustomobject]@{ Hex = ('{0:X8}' -f $h); Count = $counted }
}
if ($lines.Count -lt 2) {
    Write-Error "$ArtifactPath is too short to carry G-EXPANDER's own header - not a real expanded artifact."
}
$fromMatch = [regex]::Match($lines[0], 'from ([^\s]+\.vla)\b')
$hashMatch = [regex]::Match($lines[1], 'source-hash:\s*([0-9A-Fa-f]{8}) over (\d+) non-whitespace bytes')
$sizeMatch = [regex]::Match($lines[1], 'source-size:\s*(\d+)\s*bytes')
if (-not $fromMatch.Success -or -not ($hashMatch.Success -or $sizeMatch.Success)) {
    Write-Error "$ArtifactPath's own header doesn't match G-EXPANDER's stamped shape - re-export via Export Expanded Vocabulary rather than hand-editing this file."
}
$sourceName = $fromMatch.Groups[1].Value
# The source may sit beside the artifact (the layout when G-EXPANDER was
# written) or under polyglotta (EDITION-MANIFEST moved every phrasebook
# there on 2026-09-01). Try both; the artifact header names only the file.
$artifactDir = Split-Path -Parent $ArtifactPath
$sourceCandidates = @((Join-Path $artifactDir $sourceName), (Join-Path (Join-Path $artifactDir 'polyglotta') $sourceName))
$sourcePath = $sourceCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
if (-not $sourcePath) {
    Write-Error "$ArtifactPath names its source as $sourceName, which is at neither $($sourceCandidates -join ' nor ') - can't verify freshness; re-export."
}
if ($hashMatch.Success) {
    $expectedHex   = $hashMatch.Groups[1].Value.ToUpperInvariant()
    $expectedCount = [long]$hashMatch.Groups[2].Value
    $actual = Get-SourceHash $sourcePath
    if ($actual.Hex -ne $expectedHex -or $actual.Count -ne $expectedCount) {
        Write-Error "$ArtifactPath is STALE: stamped source-hash $expectedHex over $expectedCount non-whitespace bytes, but $sourceName hashes to $($actual.Hex) over $($actual.Count) now - a token changed, not just whitespace. Re-export via Export Expanded Vocabulary before trusting this report."
    }
} else {
    # Legacy stamp (pre-0.5.1 export): byte-size comparison, exactly as before.
    $expectedSize = [long]$sizeMatch.Groups[1].Value
    $actualSize = (Get-Item -LiteralPath $sourcePath).Length
    if ($actualSize -ne $expectedSize) {
        Write-Error "$ArtifactPath is STALE: stamped source-size $expectedSize bytes, but $sourceName is $actualSize bytes now (legacy byte-size stamp - whitespace-only edits trip it; the next re-export switches to the whitespace-insensitive source-hash). Re-export via Export Expanded Vocabulary before trusting this report."
    }
    Write-Output "note: $ArtifactPath carries the legacy source-size stamp; the next Export Expanded Phrasebook replaces it with source-hash."
}

# --- Form-boundary scan ------------------------------------------------------
$formHeadRe = '^\(([A-Za-z][\w-]*)'
$rowTagRe   = '^;\s*row:\s*(.+)$'

class RuleEntry {
    [string]$Pattern
    [string]$RowTag
    [int]$TestCount
    [int]$Ordinal
}

$rules = New-Object System.Collections.Generic.List[RuleEntry]
$orphanTests = New-Object System.Collections.Generic.List[string]
$testFailCount = 0
$unknownForms = New-Object System.Collections.Generic.List[string]
$currentRule = $null
$pendingRowTag = ''
$ordinal = 0

for ($li = 0; $li -lt $lines.Count; $li++) {
    $line = $lines[$li]
    $rowM = [regex]::Match($line, $rowTagRe)
    if ($rowM.Success) {
        $pendingRowTag = $rowM.Groups[1].Value
        continue
    }

    $headM = [regex]::Match($line, $formHeadRe)
    if (-not $headM.Success) {
        # header lines, blank lines, or a continuation line of a
        # multi-line (verticalized) form - never a new form boundary.
        continue
    }
    $head = $headM.Groups[1].Value
    $ordinal++

    switch -Regex ($head) {
        '^english-vla(-override)?$' {
            $patM = [regex]::Match($line, '^\(english-vla(?:-override)?\s+"((?:[^"\\]|\\.)*)"')
            if (-not $patM.Success) {
                # Verticalized form (GEXPANDERLINT.0's house layout - the real
                # artifact since 2026-08-25): the head sits alone on its line
                # and the pattern string is the first thing on the next. Read
                # ahead a few lines for the first line that opens with a
                # string literal. Found 2026-09-07: this branch was missing,
                # so every rule printed "(pattern unreadable)" - unnoticed
                # because the byte-size staleness gate above rarely let the
                # script run this far.
                for ($k = $li + 1; $k -lt $lines.Count -and $k -le $li + 3; $k++) {
                    $lookM = [regex]::Match($lines[$k], '^\s*"((?:[^"\\]|\\.)*)"')
                    if ($lookM.Success) { $patM = $lookM; break }
                }
            }
            $entry = [RuleEntry]::new()
            $entry.Pattern = if ($patM.Success) { $patM.Groups[1].Value } else { '(pattern unreadable)' }
            $entry.RowTag = $pendingRowTag
            $entry.TestCount = 0
            $entry.Ordinal = $ordinal
            $rules.Add($entry)
            $currentRule = $entry
        }
        '^test-success$' {
            if ($currentRule) {
                $currentRule.TestCount++
            } else {
                $sentM = [regex]::Match($line, '^\(test-success\s+"((?:[^"\\]|\\.)*)"')
                $orphanTests.Add($(if ($sentM.Success) { $sentM.Groups[1].Value } else { $line }))
            }
        }
        '^test-fail$' {
            $testFailCount++
        }
        '^(defmacro|english-function|keyword-alias)$' {
            # not owners - never reset currentRule (a defmacro helper can
            # sit before the rule it supports, e.g. set-formula ahead of
            # its own english-vla rule in the real corpus). keyword-alias
            # (LX5.1) is a language file's own control-flow vocabulary,
            # not a phrase rule - same non-owner treatment as defmacro.
        }
        default {
            $unknownForms.Add("line with head '$head': $line")
        }
    }
    $pendingRowTag = ''
}

# --- Report -------------------------------------------------------------
Write-Output '=== PROOF COVERAGE (test-success density over the expanded phrasebook) ==='
Write-Output "Artifact: $ArtifactPath"
if ($hashMatch.Success) {
    Write-Output "Source verified fresh: $sourceName (source-hash $expectedHex over $expectedCount non-whitespace bytes)"
} else {
    Write-Output "Source verified fresh: $sourceName ($actualSize bytes, legacy source-size stamp)"
}
Write-Output "Rules scanned: $($rules.Count)"
Write-Output ''

$zero = $rules | Where-Object { $_.TestCount -eq 0 }
Write-Output "--- Zero tests, $($zero.Count) rule(s) ---"
$zero | ForEach-Object {
    $tag = if ($_.RowTag) { " [from $($_.RowTag)]" } else { '' }
    Write-Output "  $($_.Pattern)$tag"
}

Write-Output ''
$one = $rules | Where-Object { $_.TestCount -eq 1 }
Write-Output "--- Exactly one test, $($one.Count) rule(s) ---"
$one | ForEach-Object {
    $tag = if ($_.RowTag) { " [from $($_.RowTag)]" } else { '' }
    Write-Output "  $($_.Pattern)$tag"
}

Write-Output ''
$twoPlus = $rules | Where-Object { $_.TestCount -ge 2 }
Write-Output "--- test-fail proofs (file-level, never attributed to a rule): $testFailCount ---"

Write-Output ''
Write-Output "--- Orphan test-success (no preceding rule - should always be empty; non-empty means a bug in G-EXPANDER or this scanner, not the grammar): $($orphanTests.Count) ---"
$orphanTests | ForEach-Object { Write-Output "  $_" }

if ($unknownForms.Count -gt 0) {
    Write-Output ''
    Write-Output "--- Unrecognized top-level forms, $($unknownForms.Count) (not one of the six known directives - investigate) ---"
    $unknownForms | ForEach-Object { Write-Output "  $_" }
}

Write-Output ''
Write-Output "=== SUMMARY: $($twoPlus.Count)/$($rules.Count) rules have 2+ tests; $($one.Count) have exactly one; $($zero.Count) have zero ==="
