<#
check_audit_golden.ps1 - the core reproduces the audit goldens whole; each
golden's line count never goes down; the fixed order holds in the golden
itself.

WHY: PORT.8 slice 8d asks Stage 2.3's audit list of a workbook's file in
the core (core/src/reflect/audit.rs), and the treaty's tenth oracle
(conformance/README.md, the amendment of 2026-10-05 for slice 8d) holds
`frazaro audit` to its own goldens: each fixture's findings, as the door
prints them, are the <name>_audit.vla beside it, whole. As with oracles 8
and 9, the VBA reference has no output to reproduce here (AXM.10's queries
over the live workbook are not built), so the goldens are the core's own
output, blessed by the owner reading the fixture in Excel, and what this
check holds is that no walk drifts from what was blessed without a
regenerated golden committed beside the change, and that a second
implementation prints the same findings.

ALSO HELD, read off each golden itself: its line count, as a floor that
never goes down (the house style's hardcoded, reviewable number); and the
fixed order the amendment fixes - every line one of the six forms, the
forms in their order (typed-over, inconsistent, unused-name,
empty-reference, hidden-sheet, external-link), the cell rows of one form
grouped by sheet and never descending in row then column, the names never
descending without case - so that a golden regenerated by a printer that
drifted fails here on every push.

WHAT IT RUNS: `<impl> audit <fixture>`, the contract's own command, on the
built door at target/debug/frazaro.exe (or target/release), or on -Impl
when given; its stdout is compared to the golden after line endings are
normalized to LF and trailing blank lines dropped, and the first differing
line is named with both texts. The door exits 0 findings or none; a tree
with no door says SKIPPED for that half and exits 0, as
check_reflect_golden.ps1 does, since CI always has it; the floors and the
order are checked either way.

-Control proves the check on fakes written to a scratch directory: one
that prints the golden beside its fixture (must pass every row); one that
changes one character of the first row of whatever it prints (must fail
every row, naming line 1); and a copy of the first golden with its first
hidden-sheet row moved to the top (the order pin must fail it, and pass the
golden as it is).

House style (tools/check_*.ps1): PowerShell 5.1, host-free, no Excel, no
COM, no network; exit 0 clean, exit 1 with every problem named. The door's
stderr is read under ErrorActionPreference Continue, as
check_reflect_golden.ps1 does.

Usage:  powershell -File tools\check_audit_golden.ps1
        powershell -File tools\check_audit_golden.ps1 -Impl C:\path\to\frazaro.exe
        powershell -File tools\check_audit_golden.ps1 -Control
#>
param(
    [string]$Impl = '',
    [switch]$Control
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- the goldens and their floors: each line count, never lowered ------------
# 2026-10-05, PORT.8 slice 8d: fixture 9 (the reader's fixture, whose Review
# sheet holds one case of each column walk and two empty references, with
# the two unused names, the two hidden sheets and the link it had); changed
# 6 (the changed copy: no hidden sheet, Deep unused, one empty reference,
# since its Model!H1 is filled); build_fixture 3 (the first build golden:
# Output!C3 and C4 refer to B4 and B5, which nothing holds). Raise a floor
# when a regenerated golden is longer; lower it only with a regenerated
# golden that is shorter, and say why.
$goldens = @(
    @{ Name = 'fixture';       Fixture = 'scripts/reflect/fixture.xlsx';      Golden = 'scripts/reflect/fixture_audit.vla';       Floor = 9 },
    @{ Name = 'changed';       Fixture = 'scripts/reflect/changed.xlsx';      Golden = 'scripts/reflect/changed_audit.vla';       Floor = 6 },
    @{ Name = 'build_fixture'; Fixture = 'scripts/build/fixture_golden.xlsx'; Golden = 'scripts/reflect/build_fixture_audit.vla'; Floor = 3 }
)

# The forms an audit prints, in the fixed order.
$phases = @{ 'typed-over' = 0; 'inconsistent' = 1; 'unused-name' = 2; 'empty-reference' = 3; 'hidden-sheet' = 4; 'external-link' = 5 }
$phaseNames = @('typed-over', 'inconsistent', 'unused-name', 'empty-reference', 'hidden-sheet', 'external-link')

# A text as its lines: line endings normalized, trailing blank lines dropped.
function Get-Lines([string]$text) {
    $t = $text -replace "`r`n", "`n"
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($l in ($t -split "`n")) { $lines.Add($l) }
    while ($lines.Count -gt 0 -and $lines[$lines.Count - 1] -eq '') { $lines.RemoveAt($lines.Count - 1) }
    return ,$lines
}

# The first quoted string of a form after its head, unescaped as WriteDatum
# escapes (`\"` and `\\`), or '' when there is none.
function Get-FirstString([string]$line) {
    $m = [regex]::Match($line, '^\([a-z-]+ "((?:[^"\\]|\\.)*)"')
    if (-not $m.Success) { return '' }
    return ($m.Groups[1].Value -replace '\\(.)', '$1')
}

# The relation a line is a row of, or '' when the line is not a row.
function Get-Relation([string]$line) {
    $m = [regex]::Match($line, '^\(([a-z-]+) ')
    if (-not $m.Success) { return '' }
    return $m.Groups[1].Value
}

# A cell key split at its last '!': the sheet with its quotes undone, and
# the address's row and column; $null when the key is not a cell.
function Split-Cell([string]$key) {
    $at = $key.LastIndexOf('!')
    if ($at -lt 0) { return $null }
    $sheet = $key.Substring(0, $at)
    if ($sheet -match "^'(.*)'$") { $sheet = $Matches[1] -replace "''", "'" }
    $m = [regex]::Match($key.Substring($at + 1), '^([A-Z]{1,3})([0-9]+)$')
    if (-not $m.Success) { return $null }
    $col = 0
    foreach ($ch in $m.Groups[1].Value.ToCharArray()) { $col = $col * 26 + ([int][char]$ch - 64) }
    return @{ Sheet = $sheet; Row = [int64]$m.Groups[2].Value; Col = [int64]$col }
}

# The fixed order, read off a golden's lines: a list of problems, empty when
# it holds.
function Test-Order($lines) {
    $problems = New-Object System.Collections.Generic.List[string]
    $phase = 0
    $ended = New-Object System.Collections.Generic.List[string]   # sheets whose rows of this form have ended
    $current = $null
    $lastRow = [int64]0; $lastCol = [int64]0
    $lastName = ''
    $n = 0
    foreach ($line in $lines) {
        $n++
        $rel = Get-Relation $line
        if ($rel -eq '' -or -not $phases.ContainsKey($rel)) { $problems.Add("line ${n}: not a finding: $line"); continue }
        $p = $phases[$rel]
        if ($p -lt $phase) { $problems.Add("line ${n}: a $($phaseNames[$p]) row after the $($phaseNames[$phase]) rows began: $line"); continue }
        if ($p -ne $phase) { $phase = $p; $ended.Clear(); $current = $null; $lastRow = [int64]0; $lastCol = [int64]0; $lastName = '' }
        $key = Get-FirstString $line
        if ($rel -eq 'unused-name') {
            if ($lastName -ne '' -and [string]::Compare($key, $lastName, [System.StringComparison]::OrdinalIgnoreCase) -lt 0) { $problems.Add("line ${n}: a name out of order: $line"); continue }
            $lastName = $key
            continue
        }
        if ($rel -eq 'hidden-sheet') { continue }
        $cell = Split-Cell $key
        if ($null -eq $cell) { $problems.Add("line ${n}: a $rel row whose first field is not a cell: $line"); continue }
        if ($cell.Sheet -ne $current) {
            if ($ended.Contains($cell.Sheet)) { $problems.Add("line ${n}: a row of sheet $($cell.Sheet) after its rows ended: $line"); continue }
            if ($null -ne $current) { $ended.Add($current) }
            $current = $cell.Sheet; $lastRow = [int64]0; $lastCol = [int64]0
        }
        if ($cell.Row -lt $lastRow -or ($cell.Row -eq $lastRow -and $cell.Col -lt $lastCol)) { $problems.Add("line ${n}: a cell out of document order on sheet $($cell.Sheet): $line"); continue }
        $lastRow = $cell.Row; $lastCol = $cell.Col
    }
    return ,$problems
}

# `<impl> <args>` with the door's stderr set aside: its exit code and every
# line of its stdout.
function Invoke-Door([string]$impl, [string[]]$doorArgs) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $global:LASTEXITCODE = 0
        $lines = & $impl @doorArgs 2>$null
        $code = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $old
    }
    if ($null -eq $code) { $code = 0 }
    $text = if ($null -eq $lines) { '' } else { (@($lines) | ForEach-Object { [string]$_ }) -join "`n" }
    return @{ ExitCode = [int]$code; Text = $text }
}

# One implementation against one golden: a list of problems, empty when its
# findings are the golden whole.
function Measure-Impl([string]$impl, $g) {
    $problems = New-Object System.Collections.Generic.List[string]
    $golden = Join-Path $repoRoot $g.Golden
    $fixture = Join-Path $repoRoot $g.Fixture
    if (-not (Test-Path $fixture)) { $problems.Add("$($g.Name): no fixture at $fixture"); return ,$problems }
    $r = Invoke-Door $impl @('audit', $fixture)
    if ($r.ExitCode -eq 3) { $problems.Add("$($g.Name): audit not attempted (exit 3), but the golden exists"); return ,$problems }
    if ($r.ExitCode -ne 0) { $problems.Add("$($g.Name): audit exited $($r.ExitCode)"); return ,$problems }
    $want = Get-Lines ([System.IO.File]::ReadAllText($golden))
    $got = Get-Lines $r.Text
    $n = [Math]::Min($want.Count, $got.Count)
    for ($i = 0; $i -lt $n; $i++) {
        if ($want[$i] -ne $got[$i]) {
            $problems.Add("$($g.Name): differs at line $($i + 1) of $($want.Count): golden $($want[$i]) / door $($got[$i])")
            return ,$problems
        }
    }
    if ($want.Count -ne $got.Count) { $problems.Add("$($g.Name): the door printed $($got.Count) lines, the golden holds $($want.Count); they agree to line $n") }
    return ,$problems
}

# Every golden's floor and order: problems, and lines to print.
function Test-Goldens() {
    $problems = New-Object System.Collections.Generic.List[string]
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($g in $goldens) {
        $path = Join-Path $repoRoot $g.Golden
        if (-not (Test-Path $path)) { $problems.Add("$($g.Name): no golden at $path"); continue }
        $rows = Get-Lines ([System.IO.File]::ReadAllText($path))
        if ($rows.Count -lt $g.Floor) {
            $problems.Add("$($g.Name): the golden holds $($rows.Count) lines, below its floor of $($g.Floor)")
            $lines.Add("  $($g.Name): $($rows.Count) lines, BELOW THE FLOOR of $($g.Floor)  FAIL")
        } elseif ($rows.Count -gt $g.Floor) {
            $lines.Add("  $($g.Name): $($rows.Count) lines, above the floor of $($g.Floor) - raise the floor in this file")
        } else {
            $lines.Add("  $($g.Name): $($g.Floor) lines, at its floor")
        }
        $order = Test-Order $rows
        foreach ($p in $order) { $problems.Add("$($g.Name): $p"); $lines.Add("  $($g.Name): $p  FAIL") }
        if ($order.Count -eq 0) { $lines.Add("  $($g.Name): the fixed order holds (the six forms in order, cells by sheet in document order, names by name)") }
    }
    return @{ Problems = $problems; Lines = $lines }
}

if ($Control) {
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('frazaro_audit_golden_' + [System.IO.Path]::GetRandomFileName())
    New-Item -ItemType Directory -Path $tmp | Out-Null
    try {
        # Both fakes: the golden beside the fixture named, by the fixture's base name.
        $map = ($goldens | ForEach-Object { "'" + [System.IO.Path]::GetFileNameWithoutExtension($_.Fixture) + "' { '" + ((Join-Path $repoRoot $_.Golden) -replace "'", "''") + "' }" }) -join '; '
        $common = "param([Parameter(ValueFromRemainingArguments=`$true)][string[]]`$a)`n" +
                  "`$base = [System.IO.Path]::GetFileNameWithoutExtension(`$a[1])`n" +
                  "`$which = switch (`$base) { $map; default { exit 3 } }`n" +
                  "`$lines = [System.IO.File]::ReadAllText(`$which) -replace `"`r`n`", `"`n`" -split `"`n`"`n"
        $fake = Join-Path $tmp 'fake.ps1'
        [System.IO.File]::WriteAllText($fake, $common + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        # The mutant changes one character of the first row it prints.
        $mut = Join-Path $tmp 'mutant.ps1'
        $flip = "if (`$lines.Count -gt 0) { `$lines[0] = `$lines[0] -replace '\)`$', 'X)' }`n"
        [System.IO.File]::WriteAllText($mut, $common + $flip + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        $fakeProblems = 0; $mutantProblems = 0; $named = $true
        foreach ($g in $goldens) {
            $r1 = Measure-Impl $fake $g
            $r2 = Measure-Impl $mut $g
            $fakeProblems += $r1.Count; $mutantProblems += $r2.Count
            if ($r2.Count -ne 1 -or -not ($r2[0] -like "*differs at line 1 of*")) { $named = $false }
            Write-Output ("control, {0}: the fake has {1} problem(s); the mutant {2}: {3}" -f $g.Name, $r1.Count, $r2.Count, ($r2 -join '; '))
        }
        # The order pin: the first golden as it is, and a copy with its first
        # hidden-sheet row moved to the top.
        $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $goldens[0].Golden)))
        $r0 = Test-Order $rows
        $moved = New-Object System.Collections.Generic.List[string]
        $hiddenRow = @($rows | Where-Object { $_ -like '(hidden-sheet *' })[0]
        $moved.Add($hiddenRow)
        foreach ($l in $rows) { if ($l -ne $hiddenRow) { $moved.Add($l) } }
        $r3 = Test-Order $moved
        Write-Output ("control: the first golden's order {0} problem(s); the moved copy {1}: {2}" -f $r0.Count, $r3.Count, ($r3 -join '; '))
        if ($fakeProblems -eq 0 -and $named -and $mutantProblems -eq $goldens.Count -and $r0.Count -eq 0 -and $r3.Count -ge 1) {
            Write-Output 'OK: the check passes every golden, fails the mutant on each naming its line, and catches a row out of order'
            exit 0
        }
        Write-Output 'FAIL: the control did not behave as the header says'
        exit 1
    } finally {
        Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    }
}

Write-Output '=== THE AUDIT GOLDENS: REPRODUCED WHOLE, NEVER SHORTER, IN THE FIXED ORDER (PORT.8 slice 8d, oracle 10) ==='
$failed = New-Object System.Collections.Generic.List[string]
$tg = Test-Goldens
$tg.Lines | ForEach-Object { Write-Output $_ }
foreach ($p in $tg.Problems) { $failed.Add($p) }

if ($Impl -eq '') {
    foreach ($candidate in @('target/debug/frazaro.exe', 'target/release/frazaro.exe', 'target/debug/frazaro', 'target/release/frazaro')) {
        $p = Join-Path $repoRoot $candidate
        if (Test-Path $p) { $Impl = $p; break }
    }
}
if ($Impl -eq '' -or -not (Test-Path $Impl)) {
    Write-Output '  SKIPPED: no built door at target/debug/frazaro.exe or target/release/frazaro.exe (cargo build --workspace writes it; CI always has it)'
} else {
    foreach ($g in $goldens) {
        $r = Measure-Impl $Impl $g
        foreach ($p in $r) { $failed.Add($p); Write-Output "  $p  FAIL" }
        if ($r.Count -eq 0) { Write-Output "  $($g.Name): the door's findings are the golden, whole" }
    }
}

Write-Output ''
if ($failed.Count -eq 0) {
    Write-Output '=== CHECK: clean - every audit golden is reproduced whole, at or above its floor, in the fixed order ==='
    exit 0
}
Write-Output "=== CHECK: $($failed.Count) problem(s) ==="
$failed | ForEach-Object { Write-Output "  $_" }
exit 1
