<#
check_view_golden.ps1 - the core reproduces the view goldens whole; each
golden's line count never goes down; the fixed order holds in the golden
itself.

WHY: KERNEL.4 projects one window of the sheet model as the view record
(core/src/view.rs), the first implementation of the kernel's projections
seam, and the treaty's eleventh oracle (conformance/README.md, the
amendment of 2026-10-07 for KERNEL.4) holds it to its own goldens: each
fixture program's window, as `frazaro view` prints it, is the .vla beside
it under scripts/view/, whole. The VBA reference draws nothing; it writes
through Excel's object model and Excel is its view. So these goldens are
the core's own output, blessed by the owner reading each against the
fixture workbook open in Excel, and what this check holds is that the
record never drifts from what was blessed without a regenerated golden
committed beside the change, and that a second implementation prints the
same lines. The cell and formula rows are the reader's own spelling, and
the core's own test holds the view of a built model to `reflect` of the
file written from it (the free oracle).

ALSO HELD, read off each golden itself: its line count, as a floor that
never goes down (the house style's hardcoded, reviewable number); and the
fixed order the amendment fixes - the sheet rows, then one window row, one
extent row and one gridlines row, the column rows, the format rows with
format 0 first and the rest ascending, then the cells in row-major order,
each cell or formula row followed by its style row and its sentence row
and nothing else, every body row on the window's sheet - so that a golden
regenerated by a printer that drifted fails here on every push.

WHAT IT RUNS: `<impl> view <program> --sheet <name> [--window <range>]
--prelude scripts/prelude.vla --phrasebook scripts/polyglotta/english.vla`,
the contract's own command over the corpus files, on the built door at
target/debug/frazaro.exe (or target/release), or on -Impl when given; its
stdout is compared to the golden after line endings are normalized to LF
and trailing blank lines dropped, and the first differing line is named
with both texts. A tree with no door says SKIPPED for that half and exits
0, as check_reflect_golden.ps1 does, since CI always has it; the floors
and the order are checked either way.

-Control proves the check on fakes written to a scratch directory: one
that prints the golden of each window (must pass every row); one that
changes one value in the first cell or formula row of whatever it prints
(must fail every row, naming that line); and a copy of the first golden
with its first format row moved below its first cell row (the order pin
must fail it, and pass the golden as it is).

House style (tools/check_*.ps1): PowerShell 5.1, host-free, no Excel, no
COM, no network; exit 0 clean, exit 1 with every problem named. The door's
stderr is read under ErrorActionPreference Continue, as
check_reflect_golden.ps1 does.

Usage:  powershell -File tools\check_view_golden.ps1
        powershell -File tools\check_view_golden.ps1 -Impl C:\path\to\frazaro.exe
        powershell -File tools\check_view_golden.ps1 -Control
#>
param(
    [string]$Impl = '',
    [switch]$Control
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- the goldens and their floors: each line count, never lowered ------------
# 2026-10-07, KERNEL.4: six windows over the two build fixtures. fixture_frazaro
# 66 (the Frazaro sheet whole: both columns with their widths and formats, the
# sentences and their OK marks, each by its own row); fixture_output 21 (A1:F20
# of Output: two values, five formulas, the shared children with their moved
# text, each by the line that wrote it); fixture_output_b2_c3 15 (the clip:
# four of those cells, the extent still whole); fixture_data 9 (the one cell
# of a sheet the program named in another case); into_output 11 and
# into_checks 9 (the second fixture viewed without its model: the formulas
# that read the model as text). 2026-10-08, KERNEL.7: a value row follows
# each formula row (SPEC decision 14): fixture_output 26, fixture_output_b2_c3
# 18, into_output 12, into_checks 10; the two sheets with no formula keep
# their counts. Raise a floor when a regenerated golden is longer; lower it
# only with a regenerated golden that is shorter, and say why.
$prelude = 'scripts/prelude.vla'
$phrasebook = 'scripts/polyglotta/english.vla'
$goldens = @(
    @{ Name = 'fixture_frazaro';      Program = 'scripts/build/fixture.txt'; Sheet = 'Frazaro'; Window = '';       Golden = 'scripts/view/fixture_frazaro.vla';      Floor = 66 },
    @{ Name = 'fixture_output';       Program = 'scripts/build/fixture.txt'; Sheet = 'Output';  Window = 'A1:F20'; Golden = 'scripts/view/fixture_output.vla';       Floor = 26 },
    @{ Name = 'fixture_output_b2_c3'; Program = 'scripts/build/fixture.txt'; Sheet = 'Output';  Window = 'B2:C3';  Golden = 'scripts/view/fixture_output_b2_c3.vla'; Floor = 18 },
    @{ Name = 'fixture_data';         Program = 'scripts/build/fixture.txt'; Sheet = 'Data';    Window = '';       Golden = 'scripts/view/fixture_data.vla';         Floor = 9 },
    @{ Name = 'into_output';          Program = 'scripts/build/into.txt';    Sheet = 'Output';  Window = '';       Golden = 'scripts/view/into_output.vla';          Floor = 12 },
    @{ Name = 'into_checks';          Program = 'scripts/build/into.txt';    Sheet = 'Checks';  Window = '';       Golden = 'scripts/view/into_checks.vla';          Floor = 10 }
)

# The forms a view record holds, and the phase each belongs to in the fixed
# order: the sheets, the window, its extent, its gridlines, the columns, the
# formats, then the body cell by cell.
$phases = @{ 'sheet' = 0; 'window' = 1; 'extent' = 2; 'gridlines' = 3; 'column' = 4; 'format' = 5; 'cell' = 6; 'formula' = 6; 'value' = 6; 'style' = 6; 'sentence' = 6 }

# A text as its lines: line endings normalized, trailing blank lines dropped.
function Get-Lines([string]$text) {
    $t = $text -replace "`r`n", "`n"
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($l in ($t -split "`n")) { $lines.Add($l) }
    while ($lines.Count -gt 0 -and $lines[$lines.Count - 1] -eq '') { $lines.RemoveAt($lines.Count - 1) }
    return ,$lines
}

# The relation a line is a row of, or '' when the line is not a row.
function Get-Relation([string]$line) {
    $m = [regex]::Match($line, '^\(([a-z]+) ')
    if (-not $m.Success) { return '' }
    return $m.Groups[1].Value
}

# The quoted strings of a form, in order, unescaped as WriteDatum escapes.
function Get-Strings([string]$line) {
    $out = New-Object System.Collections.Generic.List[string]
    foreach ($m in [regex]::Matches($line, '"((?:[^"\\]|\\.)*)"')) { $out.Add(($m.Groups[1].Value -replace '\\(.)', '$1')) }
    return ,$out
}

# An A1 address as (row, column), or $null.
function Get-RowCol([string]$addr) {
    $m = [regex]::Match($addr, '^([A-Z]+)([0-9]+)$')
    if (-not $m.Success) { return $null }
    $col = 0
    foreach ($ch in $m.Groups[1].Value.ToCharArray()) { $col = $col * 26 + ([int][char]$ch - [int][char]'A' + 1) }
    return @([int]$m.Groups[2].Value, $col)
}

# The fixed order, read off a golden's lines: a list of problems, empty when
# it holds.
function Test-Order($lines) {
    $problems = New-Object System.Collections.Generic.List[string]
    $phase = 0
    $windowSheet = $null
    $seen = @{ 'window' = 0; 'extent' = 0; 'gridlines' = 0 }
    $lastFormat = -1
    $lastCell = $null      # (row, col) of the last cell or formula row
    $open = ''             # the address whose value, style and sentence rows may follow
    $isFormula = $false    # whether a value row may follow (KERNEL.7)
    $hadValue = $false; $hadStyle = $false; $hadSentence = $false
    $n = 0
    foreach ($line in $lines) {
        $n++
        $rel = Get-Relation $line
        if ($rel -eq '' -or -not $phases.ContainsKey($rel)) { $problems.Add("line ${n}: not a row of the view record: $line"); continue }
        $p = $phases[$rel]
        if ($p -lt $phase) { $problems.Add("line ${n}: a $rel row after a later phase began: $line"); continue }
        $strings = Get-Strings $line
        switch ($rel) {
            'sheet' { }
            'window' { $seen['window']++; $windowSheet = $strings[0] }
            'extent' { $seen['extent']++; if ($strings[0] -ne $windowSheet) { $problems.Add("line ${n}: the extent names another sheet than the window: $line") } }
            'gridlines' { $seen['gridlines']++; if ($strings[0] -ne $windowSheet) { $problems.Add("line ${n}: the gridlines row names another sheet than the window: $line") } }
            'column' { if ($strings[0] -ne $windowSheet) { $problems.Add("line ${n}: a column of another sheet than the window: $line") } }
            'format' {
                $m = [regex]::Match($line, '^\(format ([0-9]+) ')
                $idx = if ($m.Success) { [int]$m.Groups[1].Value } else { -1 }
                if ($lastFormat -eq -1 -and $idx -ne 0) { $problems.Add("line ${n}: the first format row is not format 0: $line") }
                elseif ($idx -le $lastFormat) { $problems.Add("line ${n}: a format row out of ascending order: $line") }
                $lastFormat = $idx
            }
            { $_ -eq 'cell' -or $_ -eq 'formula' } {
                if ($lastFormat -eq -1) { $problems.Add("line ${n}: a cell before any format row: $line") }
                if ($strings[0] -ne $windowSheet) { $problems.Add("line ${n}: a cell of another sheet than the window: $line") }
                $rc = Get-RowCol $strings[1]
                if ($null -eq $rc) { $problems.Add("line ${n}: not an address: $line") }
                elseif ($null -ne $lastCell -and ($rc[0] -lt $lastCell[0] -or ($rc[0] -eq $lastCell[0] -and $rc[1] -le $lastCell[1]))) { $problems.Add("line ${n}: a cell out of row-major order: $line") }
                $lastCell = $rc; $open = $strings[1]; $isFormula = ($rel -eq 'formula'); $hadValue = $false; $hadStyle = $false; $hadSentence = $false
            }
            'value' {
                if ($strings[0] -ne $windowSheet -or $strings[1] -ne $open -or -not $isFormula -or $hadValue -or $hadStyle -or $hadSentence) { $problems.Add("line ${n}: a value row not right after its formula: $line") }
                $hadValue = $true
            }
            'style' {
                if ($strings[0] -ne $windowSheet -or $strings[1] -ne $open -or $hadStyle -or $hadSentence) { $problems.Add("line ${n}: a style row not right after its cell (and its value row): $line") }
                $hadStyle = $true
            }
            'sentence' {
                if ($strings[0] -ne $windowSheet -or $strings[1] -ne $open -or $hadSentence) { $problems.Add("line ${n}: a sentence row not after its cell (and its style row): $line") }
                $hadSentence = $true
            }
        }
        $phase = $p
    }
    foreach ($k in @('window', 'extent', 'gridlines')) {
        if ($seen[$k] -ne 1) { $problems.Add("the golden holds $($seen[$k]) $k row(s), not one") }
    }
    return ,$problems
}

# `<impl> <args>` with the door's stderr set aside: its exit code and every
# line of its stdout.
function Invoke-Door([string]$impl, [string[]]$doorArgs) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $global:LASTEXITCODE = 0
        $lines = & $impl @doorArgs 2>$null
        $code = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $old
    }
    if ($null -eq $code) { $code = 0 }
    $text = if ($null -eq $lines) { '' } else { (@($lines) | ForEach-Object { [string]$_ }) -join "`n" }
    return @{ ExitCode = [int]$code; Text = $text }
}

# The door's arguments for one golden's window.
function Get-ViewArgs($g) {
    $viewArgs = @('view', (Join-Path $repoRoot $g.Program), '--sheet', $g.Sheet)
    if ($g.Window -ne '') { $viewArgs += @('--window', $g.Window) }
    $viewArgs += @('--prelude', (Join-Path $repoRoot $prelude), '--phrasebook', (Join-Path $repoRoot $phrasebook))
    return ,$viewArgs
}

# One implementation against one golden: a list of problems, empty when its
# record is the golden whole.
function Measure-Impl([string]$impl, $g) {
    $problems = New-Object System.Collections.Generic.List[string]
    $golden = Join-Path $repoRoot $g.Golden
    $program = Join-Path $repoRoot $g.Program
    if (-not (Test-Path $program)) { $problems.Add("$($g.Name): no program at $program"); return ,$problems }
    $r = Invoke-Door $impl (Get-ViewArgs $g)
    if ($r.ExitCode -eq 3) { $problems.Add("$($g.Name): view not attempted (exit 3), but the golden exists"); return ,$problems }
    if ($r.ExitCode -ne 0) { $problems.Add("$($g.Name): view exited $($r.ExitCode)"); return ,$problems }
    $want = Get-Lines ([System.IO.File]::ReadAllText($golden))
    $got = Get-Lines $r.Text
    $n = [Math]::Min($want.Count, $got.Count)
    for ($i = 0; $i -lt $n; $i++) {
        if ($want[$i] -ne $got[$i]) {
            $problems.Add("$($g.Name): differs at line $($i + 1) of $($want.Count): golden $($want[$i]) / door $($got[$i])")
            return ,$problems
        }
    }
    if ($want.Count -ne $got.Count) { $problems.Add("$($g.Name): the door printed $($got.Count) lines, the golden holds $($want.Count); they agree to line $n") }
    return ,$problems
}

# Every golden's floor and order: problems, and lines to print.
function Test-Goldens() {
    $problems = New-Object System.Collections.Generic.List[string]
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($g in $goldens) {
        $path = Join-Path $repoRoot $g.Golden
        if (-not (Test-Path $path)) { $problems.Add("$($g.Name): no golden at $path"); continue }
        $rows = Get-Lines ([System.IO.File]::ReadAllText($path))
        if ($rows.Count -lt $g.Floor) {
            $problems.Add("$($g.Name): the golden holds $($rows.Count) lines, below its floor of $($g.Floor)")
            $lines.Add("  $($g.Name): $($rows.Count) lines, BELOW THE FLOOR of $($g.Floor)  FAIL")
        } elseif ($rows.Count -gt $g.Floor) {
            $lines.Add("  $($g.Name): $($rows.Count) lines, above the floor of $($g.Floor) - raise the floor in this file")
        } else {
            $lines.Add("  $($g.Name): $($g.Floor) lines, at its floor")
        }
        $order = Test-Order $rows
        foreach ($p in $order) { $problems.Add("$($g.Name): $p"); $lines.Add("  $($g.Name): $p  FAIL") }
        if ($order.Count -eq 0) { $lines.Add("  $($g.Name): the fixed order holds (sheets, window, extent, gridlines, columns, formats, then the cells in row order, each formula with its value)") }
    }
    return @{ Problems = $problems; Lines = $lines }
}

if ($Control) {
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('frazaro_view_golden_' + [System.IO.Path]::GetRandomFileName())
    New-Item -ItemType Directory -Path $tmp | Out-Null
    try {
        # Both fakes: the golden of the window asked for, by the program's
        # base name, the sheet and the window.
        $map = ($goldens | ForEach-Object { "'" + [System.IO.Path]::GetFileNameWithoutExtension($_.Program) + '|' + $_.Sheet + '|' + $_.Window + "' { '" + ((Join-Path $repoRoot $_.Golden) -replace "'", "''") + "' }" }) -join '; '
        $common = "param([Parameter(ValueFromRemainingArguments=`$true)][string[]]`$a)`n" +
                  "`$base = [System.IO.Path]::GetFileNameWithoutExtension(`$a[1])`n" +
                  "`$sheet = ''; `$window = ''`n" +
                  "for (`$i = 2; `$i -lt `$a.Count - 1; `$i++) { if (`$a[`$i] -eq '--sheet') { `$sheet = `$a[`$i + 1] }; if (`$a[`$i] -eq '--window') { `$window = `$a[`$i + 1] } }`n" +
                  "`$which = switch (`"`$base|`$sheet|`$window`") { $map; default { exit 3 } }`n" +
                  "`$lines = [System.IO.File]::ReadAllText(`$which) -replace `"`r`n`", `"`n`" -split `"`n`"`n"
        $fake = Join-Path $tmp 'fake.ps1'
        [System.IO.File]::WriteAllText($fake, $common + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        # The mutant changes one value in the first cell or formula row it prints.
        $mut = Join-Path $tmp 'mutant.ps1'
        $flip = "for (`$i = 0; `$i -lt `$lines.Count; `$i++) { if (`$lines[`$i] -like '(cell *' -or `$lines[`$i] -like '(formula *') { `$lines[`$i] = `$lines[`$i] -replace '\)`$', 'X)'; break } }`n"
        [System.IO.File]::WriteAllText($mut, $common + $flip + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        $fakeProblems = 0; $mutantProblems = 0; $named = $true
        foreach ($g in $goldens) {
            $r1 = Measure-Impl $fake $g
            $r2 = Measure-Impl $mut $g
            $fakeProblems += $r1.Count; $mutantProblems += $r2.Count
            $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $g.Golden)))
            $firstCell = 0
            for ($i = 0; $i -lt $rows.Count; $i++) { if ($rows[$i] -like '(cell *' -or $rows[$i] -like '(formula *') { $firstCell = $i + 1; break } }
            if ($r2.Count -ne 1 -or -not ($r2[0] -like "*differs at line $firstCell of*")) { $named = $false }
            Write-Output ("control, {0}: the fake has {1} problem(s); the mutant {2}: {3}" -f $g.Name, $r1.Count, $r2.Count, ($r2 -join '; '))
        }
        # The order pin: the first golden as it is, and a copy with its first
        # format row moved below its first cell row.
        $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $goldens[0].Golden)))
        $r0 = Test-Order $rows
        $formatRow = @($rows | Where-Object { $_ -like '(format *' })[0]
        $moved = New-Object System.Collections.Generic.List[string]
        $placed = $false
        foreach ($l in $rows) {
            if ($l -eq $formatRow) { continue }
            $moved.Add($l)
            if (-not $placed -and $l -like '(cell *') { $moved.Add($formatRow); $placed = $true }
        }
        $r3 = Test-Order $moved
        Write-Output ("control: the first golden's order {0} problem(s); the moved copy {1}: {2}" -f $r0.Count, $r3.Count, ($r3 -join '; '))
        if ($fakeProblems -eq 0 -and $named -and $mutantProblems -eq $goldens.Count -and $r0.Count -eq 0 -and $r3.Count -ge 1) {
            Write-Output 'OK: the check passes every golden, fails the mutant on each naming its line, and catches a row out of order'
            exit 0
        }
        Write-Output 'FAIL: the control did not behave as the header says'
        exit 1
    } finally {
        Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    }
}

Write-Output '=== THE VIEW GOLDENS: REPRODUCED WHOLE, NEVER SHORTER, IN THE FIXED ORDER (KERNEL.4, oracle 11) ==='
$failed = New-Object System.Collections.Generic.List[string]
$tg = Test-Goldens
$tg.Lines | ForEach-Object { Write-Output $_ }
foreach ($p in $tg.Problems) { $failed.Add($p) }

if ($Impl -eq '') {
    foreach ($candidate in @('target/debug/frazaro.exe', 'target/release/frazaro.exe', 'target/debug/frazaro', 'target/release/frazaro')) {
        $p = Join-Path $repoRoot $candidate
        if (Test-Path $p) { $Impl = $p; break }
    }
}
if ($Impl -eq '' -or -not (Test-Path $Impl)) {
    Write-Output '  SKIPPED: no built door at target/debug/frazaro.exe or target/release/frazaro.exe (cargo build --workspace writes it; CI always has it)'
} else {
    foreach ($g in $goldens) {
        $r = Measure-Impl $Impl $g
        foreach ($p in $r) { $failed.Add($p); Write-Output "  $p  FAIL" }
        if ($r.Count -eq 0) { Write-Output "  $($g.Name): the door's record is the golden, whole" }
    }
}

Write-Output ''
if ($failed.Count -eq 0) {
    Write-Output '=== CHECK: clean - every view golden is reproduced whole, at or above its floor, in the fixed order ==='
    exit 0
}
Write-Output "=== CHECK: $($failed.Count) problem(s) ==="
$failed | ForEach-Object { Write-Output "  $_" }
exit 1
