<#
check_reflect_golden.ps1 - the core reproduces the reflect goldens whole;
each golden's line count never goes down; the fixed order holds in the
golden itself.

WHY: PORT.8 reads workbooks in the core (core/src/reflect), and the treaty's
eighth oracle (conformance/README.md, the amendment of 2026-10-03 for
PORT.8) holds the reader to its own goldens: each fixture workbook's
relations, as `frazaro reflect` prints them, are the <name>_relations.vla
beside it, whole. The VBA reference reads a workbook through Excel's object
model and never opens the file, so these goldens are not the reference's:
they are the core's own output, blessed by the owner opening each fixture
in Excel and reading it by eye, and what this check holds is that the
reader never drifts from what was blessed without a regenerated golden
committed beside the change, and that a second implementation of the
reader prints the same rows.

ALSO HELD, read off each golden itself: its line count, as a floor that
never goes down (the house style's hardcoded, reviewable number); and the
fixed order the amendment fixes - every line one of the relation forms,
the sheet rows first, then name, then table, then the cell, formula and
refers rows grouped by sheet in the order the sheet rows gave - so that a
golden regenerated by a printer that drifted fails here on every push.

WHAT IT RUNS: `<impl> reflect <fixture>`, the contract's own command, on
the built door at target/debug/frazaro.exe (or target/release), or on -Impl
when given; its stdout is compared to the golden after line endings are
normalized to LF and trailing blank lines dropped, and the first differing
line is named with both texts. A tree with no door says SKIPPED for that
half and exits 0, as check_core_imports.ps1 does, since CI always has it;
the floors and the order are checked either way.

-Control proves the check on fakes written to a scratch directory: one
that prints the golden beside its fixture (must pass every row); one that
changes one value in the first cell row of whatever it prints (must fail
every row, naming that line); and a copy of the first golden with its
first name row moved above the sheet rows (the order pin must fail it, and
pass the golden as it is).

House style (tools/check_*.ps1): PowerShell 5.1, host-free, no Excel, no
COM, no network; exit 0 clean, exit 1 with every problem named. The door's
stderr is read under ErrorActionPreference Continue, as
check_build_golden.ps1 does. The fixtures may be open in Excel while the
owner reads them: the door opens a file with sharing that tolerates that,
and this check reads only the text goldens itself.

Usage:  powershell -File tools\check_reflect_golden.ps1
        powershell -File tools\check_reflect_golden.ps1 -Impl C:\path\to\frazaro.exe
        powershell -File tools\check_reflect_golden.ps1 -Control
#>
param(
    [string]$Impl = '',
    [switch]$Control
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- the goldens and their floors: each line count, never lowered ------------
# 2026-10-03, PORT.8 slice 8a: fixture 70 (the reader's own fixture, every
# case the walker has an arm for); build_fixture 30 and build_into 30 (the
# two build goldens read back); model 11 (the model the into golden was built
# into). Raise a floor when a regenerated golden is longer; lower it only
# with a regenerated golden that is shorter, and say why.
# 2026-10-04, PORT.8 slice 8a, the owner's live pass: saved 35 - the first
# build golden saved by Excel 365 (scripts/reflect/saved.xlsx, the host's
# save, kept as it was like model.xlsx): the same rows plus a cell row for
# each formula's cached value, and the stamp's text constant, longer than
# 255 characters, rewritten by Excel as _xlfn._LONGTEXT("...","...").
$goldens = @(
    # 2026-10-04, PORT.8 slice 8b: the refers rows join every formula (20, 8,
    # 5, 2 and 8 of them), so 70 -> 90, 30 -> 38, 30 -> 35, 11 -> 13, 35 -> 43.
    @{ Name = 'fixture';       Fixture = 'scripts/reflect/fixture.xlsx';      Golden = 'scripts/reflect/fixture_relations.vla';       Floor = 90 },
    @{ Name = 'build_fixture'; Fixture = 'scripts/build/fixture_golden.xlsx'; Golden = 'scripts/reflect/build_fixture_relations.vla'; Floor = 38 },
    @{ Name = 'build_into';    Fixture = 'scripts/build/into_golden.xlsx';    Golden = 'scripts/reflect/build_into_relations.vla';    Floor = 35 },
    @{ Name = 'model';         Fixture = 'scripts/build/model.xlsx';          Golden = 'scripts/reflect/model_relations.vla';         Floor = 13 },
    @{ Name = 'saved';         Fixture = 'scripts/reflect/saved.xlsx';        Golden = 'scripts/reflect/saved_relations.vla';         Floor = 43 }
)

# The relation forms a reader prints, and the phase each belongs to in the
# fixed order: the sheet rows, then the names, then the Tables, then the
# body, cell by cell.
$phases = @{ 'sheet' = 0; 'name' = 1; 'table' = 2; 'cell' = 3; 'formula' = 3; 'refers' = 3 }

# A text as its lines: line endings normalized, trailing blank lines dropped.
function Get-Lines([string]$text) {
    $t = $text -replace "`r`n", "`n"
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($l in ($t -split "`n")) { $lines.Add($l) }
    while ($lines.Count -gt 0 -and $lines[$lines.Count - 1] -eq '') { $lines.RemoveAt($lines.Count - 1) }
    return ,$lines
}

# The first quoted string of a form after its head, unescaped as WriteDatum
# escapes (`\"` and `\\`), or '' when there is none.
function Get-FirstString([string]$line) {
    $m = [regex]::Match($line, '^\([a-z]+ "((?:[^"\\]|\\.)*)"')
    if (-not $m.Success) { return '' }
    return ($m.Groups[1].Value -replace '\\(.)', '$1')
}

# The relation a line is a row of, or '' when the line is not a row.
function Get-Relation([string]$line) {
    $m = [regex]::Match($line, '^\(([a-z]+) ')
    if (-not $m.Success) { return '' }
    return $m.Groups[1].Value
}

# The fixed order, read off a golden's lines: a list of problems, empty when
# it holds.
function Test-Order($lines) {
    $problems = New-Object System.Collections.Generic.List[string]
    $sheets = New-Object System.Collections.Generic.List[string]
    $phase = 0
    $sheetAt = 0   # the index into $sheets the body has reached
    $n = 0
    foreach ($line in $lines) {
        $n++
        $rel = Get-Relation $line
        if ($rel -eq '' -or -not $phases.ContainsKey($rel)) { $problems.Add("line ${n}: not a relation row: $line"); continue }
        $p = $phases[$rel]
        if ($p -lt $phase) { $problems.Add("line ${n}: a $rel row after the $(@($phases.Keys | Where-Object { $phases[$_] -eq $phase })[0]) rows began: $line"); continue }
        $phase = $p
        if ($rel -eq 'sheet') { $sheets.Add((Get-FirstString $line)); continue }
        if ($p -ne 3) { continue }
        $sheet = Get-FirstString $line
        if ($rel -eq 'refers') { $sheet = ($sheet -split '!')[0] -replace "^'(.*)'$", '$1' -replace "''", "'" }
        $idx = $sheets.IndexOf($sheet)
        if ($idx -lt 0) { $problems.Add("line ${n}: a row of a sheet no sheet row named: $line"); continue }
        if ($idx -lt $sheetAt) { $problems.Add("line ${n}: a row of sheet $sheet after a later sheet's rows: $line"); continue }
        $sheetAt = $idx
    }
    return ,$problems
}

# `<impl> <args>` with the door's stderr set aside: its exit code and every
# line of its stdout.
function Invoke-Door([string]$impl, [string[]]$doorArgs) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $global:LASTEXITCODE = 0
        $lines = & $impl @doorArgs 2>$null
        $code = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $old
    }
    if ($null -eq $code) { $code = 0 }
    $text = if ($null -eq $lines) { '' } else { (@($lines) | ForEach-Object { [string]$_ }) -join "`n" }
    return @{ ExitCode = [int]$code; Text = $text }
}

# One implementation against one golden: a list of problems, empty when its
# relations are the golden whole.
function Measure-Impl([string]$impl, $g) {
    $problems = New-Object System.Collections.Generic.List[string]
    $golden = Join-Path $repoRoot $g.Golden
    $fixture = Join-Path $repoRoot $g.Fixture
    if (-not (Test-Path $fixture)) { $problems.Add("$($g.Name): no fixture at $fixture"); return ,$problems }
    $r = Invoke-Door $impl @('reflect', $fixture)
    if ($r.ExitCode -eq 3) { $problems.Add("$($g.Name): reflect not attempted (exit 3), but the golden exists"); return ,$problems }
    if ($r.ExitCode -ne 0) { $problems.Add("$($g.Name): reflect exited $($r.ExitCode)"); return ,$problems }
    $want = Get-Lines ([System.IO.File]::ReadAllText($golden))
    $got = Get-Lines $r.Text
    $n = [Math]::Min($want.Count, $got.Count)
    for ($i = 0; $i -lt $n; $i++) {
        if ($want[$i] -ne $got[$i]) {
            $problems.Add("$($g.Name): differs at line $($i + 1) of $($want.Count): golden $($want[$i]) / door $($got[$i])")
            return ,$problems
        }
    }
    if ($want.Count -ne $got.Count) { $problems.Add("$($g.Name): the door printed $($got.Count) lines, the golden holds $($want.Count); they agree to line $n") }
    return ,$problems
}

# Every golden's floor and order: problems, and lines to print.
function Test-Goldens() {
    $problems = New-Object System.Collections.Generic.List[string]
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($g in $goldens) {
        $path = Join-Path $repoRoot $g.Golden
        if (-not (Test-Path $path)) { $problems.Add("$($g.Name): no golden at $path"); continue }
        $rows = Get-Lines ([System.IO.File]::ReadAllText($path))
        if ($rows.Count -lt $g.Floor) {
            $problems.Add("$($g.Name): the golden holds $($rows.Count) lines, below its floor of $($g.Floor)")
            $lines.Add("  $($g.Name): $($rows.Count) lines, BELOW THE FLOOR of $($g.Floor)  FAIL")
        } elseif ($rows.Count -gt $g.Floor) {
            $lines.Add("  $($g.Name): $($rows.Count) lines, above the floor of $($g.Floor) - raise the floor in this file")
        } else {
            $lines.Add("  $($g.Name): $($g.Floor) lines, at its floor")
        }
        $order = Test-Order $rows
        foreach ($p in $order) { $problems.Add("$($g.Name): $p"); $lines.Add("  $($g.Name): $p  FAIL") }
        if ($order.Count -eq 0) { $lines.Add("  $($g.Name): the fixed order holds (sheets, names, tables, then the cells sheet by sheet)") }
    }
    return @{ Problems = $problems; Lines = $lines }
}

if ($Control) {
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('frazaro_reflect_golden_' + [System.IO.Path]::GetRandomFileName())
    New-Item -ItemType Directory -Path $tmp | Out-Null
    try {
        # Both fakes: the golden beside the fixture named, by the fixture's base name.
        $map = ($goldens | ForEach-Object { "'" + [System.IO.Path]::GetFileNameWithoutExtension($_.Fixture) + "' { '" + ((Join-Path $repoRoot $_.Golden) -replace "'", "''") + "' }" }) -join '; '
        $common = "param([Parameter(ValueFromRemainingArguments=`$true)][string[]]`$a)`n" +
                  "`$base = [System.IO.Path]::GetFileNameWithoutExtension(`$a[1])`n" +
                  "`$which = switch (`$base) { $map; default { exit 3 } }`n" +
                  "`$lines = [System.IO.File]::ReadAllText(`$which) -replace `"`r`n`", `"`n`" -split `"`n`"`n"
        $fake = Join-Path $tmp 'fake.ps1'
        [System.IO.File]::WriteAllText($fake, $common + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        # The mutant changes one value in the first cell row it prints.
        $mut = Join-Path $tmp 'mutant.ps1'
        $flip = "for (`$i = 0; `$i -lt `$lines.Count; `$i++) { if (`$lines[`$i] -like '(cell *') { `$lines[`$i] = `$lines[`$i] -replace '\)`$', 'X)'; break } }`n"
        [System.IO.File]::WriteAllText($mut, $common + $flip + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        $fakeProblems = 0; $mutantProblems = 0; $named = $true
        foreach ($g in $goldens) {
            $r1 = Measure-Impl $fake $g
            $r2 = Measure-Impl $mut $g
            $fakeProblems += $r1.Count; $mutantProblems += $r2.Count
            $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $g.Golden)))
            $firstCell = 0
            for ($i = 0; $i -lt $rows.Count; $i++) { if ($rows[$i] -like '(cell *') { $firstCell = $i + 1; break } }
            if ($r2.Count -ne 1 -or -not ($r2[0] -like "*differs at line $firstCell of*")) { $named = $false }
            Write-Output ("control, {0}: the fake has {1} problem(s); the mutant {2}: {3}" -f $g.Name, $r1.Count, $r2.Count, ($r2 -join '; '))
        }
        # The order pin: the first golden as it is, and a copy with its first
        # name row moved above the sheet rows.
        $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $goldens[0].Golden)))
        $r0 = Test-Order $rows
        $moved = New-Object System.Collections.Generic.List[string]
        $nameRow = @($rows | Where-Object { $_ -like '(name *' })[0]
        $moved.Add($nameRow)
        foreach ($l in $rows) { if ($l -ne $nameRow) { $moved.Add($l) } }
        $r3 = Test-Order $moved
        Write-Output ("control: the first golden's order {0} problem(s); the moved copy {1}: {2}" -f $r0.Count, $r3.Count, ($r3 -join '; '))
        if ($fakeProblems -eq 0 -and $named -and $mutantProblems -eq $goldens.Count -and $r0.Count -eq 0 -and $r3.Count -ge 1) {
            Write-Output 'OK: the check passes every golden, fails the mutant on each naming its line, and catches a row out of order'
            exit 0
        }
        Write-Output 'FAIL: the control did not behave as the header says'
        exit 1
    } finally {
        Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    }
}

Write-Output '=== THE REFLECT GOLDENS: REPRODUCED WHOLE, NEVER SHORTER, IN THE FIXED ORDER (PORT.8, oracle 8) ==='
$failed = New-Object System.Collections.Generic.List[string]
$tg = Test-Goldens
$tg.Lines | ForEach-Object { Write-Output $_ }
foreach ($p in $tg.Problems) { $failed.Add($p) }

if ($Impl -eq '') {
    foreach ($candidate in @('target/debug/frazaro.exe', 'target/release/frazaro.exe', 'target/debug/frazaro', 'target/release/frazaro')) {
        $p = Join-Path $repoRoot $candidate
        if (Test-Path $p) { $Impl = $p; break }
    }
}
if ($Impl -eq '' -or -not (Test-Path $Impl)) {
    Write-Output '  SKIPPED: no built door at target/debug/frazaro.exe or target/release/frazaro.exe (cargo build --workspace writes it; CI always has it)'
} else {
    foreach ($g in $goldens) {
        $r = Measure-Impl $Impl $g
        foreach ($p in $r) { $failed.Add($p); Write-Output "  $p  FAIL" }
        if ($r.Count -eq 0) { Write-Output "  $($g.Name): the door's relations are the golden, whole" }
    }
}

Write-Output ''
if ($failed.Count -eq 0) {
    Write-Output '=== CHECK: clean - every reflect golden is reproduced whole, at or above its floor, in the fixed order ==='
    exit 0
}
Write-Output "=== CHECK: $($failed.Count) problem(s) ==="
$failed | ForEach-Object { Write-Output "  $_" }
exit 1
