<#
check_diff_golden.ps1 - the core reproduces the diff goldens whole; each
golden's line count never goes down; the fixed order holds in the golden
itself.

WHY: PORT.8 slice 8c compares two workbooks in the core
(core/src/reflect/diff.rs), and the treaty's ninth oracle
(conformance/README.md, the amendment of 2026-10-04 for slice 8c) holds
`frazaro diff` to its own goldens: each pair of fixture workbooks'
difference, as the door prints it, is the <old>_<new>_diff.vla beside them,
whole. As with oracle 8, the VBA reference has no output to reproduce here
(AXM.11's DIFF over COM is not built), so the goldens are the core's own
output, blessed by the owner reading both files of each pair in Excel, and
what this check holds is that the comparison never drifts from what was
blessed without a regenerated golden committed beside the change, and that
a second implementation prints the same rows.

ALSO HELD, read off each golden itself: its line count, as a floor that
never goes down (the house style's hardcoded, reviewable number); and the
fixed order the amendment fixes - every line one of the four forms, the
sheet-removed rows first, then sheet-added, then sheet-changed, then the
changed rows whose key is a name or a Table (a key not shaped like a cell:
LX.13's rule, that a name is never shaped like a cell, read backwards),
then the cell rows grouped by sheet, each sheet's rows together and
ascending in row then column - so that a golden regenerated by a printer
that drifted fails here on every push.

WHAT IT RUNS: `<impl> diff <old> <new>`, the contract's own command, on the
built door at target/debug/frazaro.exe (or target/release), or on -Impl
when given; its stdout is compared to the golden after line endings are
normalized to LF and trailing blank lines dropped, and the first differing
line is named with both texts. The door exits 0 whether or not the files
differ (the rows are the answer); a tree with no door says SKIPPED for that
half and exits 0, as check_reflect_golden.ps1 does, since CI always has it;
the floors and the order are checked either way.

-Control proves the check on fakes written to a scratch directory: one
that prints the golden beside its pair (must pass every row); one that
changes one value in the first changed row of whatever it prints (must fail
every row, naming that line); and a copy of the third golden with its first
sheet-added row moved to the end (the order pin must fail it, and pass the
golden as it is).

House style (tools/check_*.ps1): PowerShell 5.1, host-free, no Excel, no
COM, no network; exit 0 clean, exit 1 with every problem named. The door's
stderr is read under ErrorActionPreference Continue, as
check_reflect_golden.ps1 does. The fixtures may be open in Excel while the
owner reads them: the door opens a file with sharing that tolerates that,
and this check reads only the text goldens itself.

Usage:  powershell -File tools\check_diff_golden.ps1
        powershell -File tools\check_diff_golden.ps1 -Impl C:\path\to\frazaro.exe
        powershell -File tools\check_diff_golden.ps1 -Control
#>
param(
    [string]$Impl = '',
    [switch]$Control
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- the goldens and their floors: each line count, never lowered ------------
# 2026-10-04, PORT.8 slice 8c: build_fixture_saved 6 (the first build golden
# against its Excel-saved copy: the stamp name's _xlfn._LONGTEXT rewrite and
# the five formulas' cached values); model_into 4 (the model against the
# into golden built into it: three sheets added and the stamp name from
# blank); fixture_changed 24 (the reader's fixture against the copy
# build_reflect_fixture.ps1 -Changed writes, one edit per arm of the
# comparison, and no row for a 800 that became 800.0). Raise a floor when a
# regenerated golden is longer; lower it only with a regenerated golden that
# is shorter, and say why.
$goldens = @(
    @{ Name = 'build_fixture_saved'; Old = 'scripts/build/fixture_golden.xlsx'; New = 'scripts/reflect/saved.xlsx';      Golden = 'scripts/reflect/build_fixture_saved_diff.vla'; Floor = 6 },
    @{ Name = 'model_into';          Old = 'scripts/build/model.xlsx';          New = 'scripts/build/into_golden.xlsx'; Golden = 'scripts/reflect/model_into_diff.vla';          Floor = 4 },
    @{ Name = 'fixture_changed';     Old = 'scripts/reflect/fixture.xlsx';      New = 'scripts/reflect/changed.xlsx';   Golden = 'scripts/reflect/fixture_changed_diff.vla';     Floor = 24 }
)

# The forms a diff prints and the phase each belongs to in the fixed order.
# A changed row is phase 3 when its key is a name or a Table, phase 4 when
# it is a cell.
$phases = @{ 'sheet-removed' = 0; 'sheet-added' = 1; 'sheet-changed' = 2; 'changed' = 3 }
$phaseNames = @('sheet-removed', 'sheet-added', 'sheet-changed', 'changed (names and Tables)', 'changed (cells)')

# A text as its lines: line endings normalized, trailing blank lines dropped.
function Get-Lines([string]$text) {
    $t = $text -replace "`r`n", "`n"
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($l in ($t -split "`n")) { $lines.Add($l) }
    while ($lines.Count -gt 0 -and $lines[$lines.Count - 1] -eq '') { $lines.RemoveAt($lines.Count - 1) }
    return ,$lines
}

# The first quoted string of a form after its head, unescaped as WriteDatum
# escapes (`\"` and `\\`), or '' when there is none.
function Get-FirstString([string]$line) {
    $m = [regex]::Match($line, '^\([a-z-]+ "((?:[^"\\]|\\.)*)"')
    if (-not $m.Success) { return '' }
    return ($m.Groups[1].Value -replace '\\(.)', '$1')
}

# The relation a line is a row of, or '' when the line is not a row.
function Get-Relation([string]$line) {
    $m = [regex]::Match($line, '^\(([a-z-]+) ')
    if (-not $m.Success) { return '' }
    return $m.Groups[1].Value
}

# A changed row's key split at its last '!': the sheet with its quotes
# undone, and the address; $null when the key has no '!' (a workbook-level
# name or a Table).
function Split-Key([string]$key) {
    $at = $key.LastIndexOf('!')
    if ($at -lt 0) { return $null }
    $sheet = $key.Substring(0, $at)
    if ($sheet -match "^'(.*)'$") { $sheet = $Matches[1] -replace "''", "'" }
    return @{ Sheet = $sheet; Addr = $key.Substring($at + 1) }
}

# An address that is a cell, letters then digits, as its row and column;
# $null for anything else (a sheet-scoped name's name, for one).
function Get-CellPosition([string]$addr) {
    $m = [regex]::Match($addr, '^([A-Z]{1,3})([0-9]+)$')
    if (-not $m.Success) { return $null }
    $col = 0
    foreach ($ch in $m.Groups[1].Value.ToCharArray()) { $col = $col * 26 + ([int][char]$ch - 64) }
    return @{ Row = [int64]$m.Groups[2].Value; Col = [int64]$col }
}

# The fixed order, read off a golden's lines: a list of problems, empty when
# it holds.
function Test-Order($lines) {
    $problems = New-Object System.Collections.Generic.List[string]
    $ended = New-Object System.Collections.Generic.List[string]   # sheets whose cell rows have ended
    $phase = 0
    $current = $null   # the sheet whose cell rows are being listed
    $lastRow = [int64]0; $lastCol = [int64]0
    $n = 0
    foreach ($line in $lines) {
        $n++
        $rel = Get-Relation $line
        if ($rel -eq '' -or -not $phases.ContainsKey($rel)) { $problems.Add("line ${n}: not a row of the difference: $line"); continue }
        $p = $phases[$rel]
        $split = $null; $pos = $null
        if ($rel -eq 'changed') {
            $split = Split-Key (Get-FirstString $line)
            if ($null -ne $split) { $pos = Get-CellPosition $split.Addr }
            if ($null -ne $pos) { $p = 4 }
        }
        if ($p -lt $phase) { $problems.Add("line ${n}: a $($phaseNames[$p]) row after the $($phaseNames[$phase]) rows began: $line"); continue }
        $phase = $p
        if ($p -ne 4) { continue }
        if ($split.Sheet -ne $current) {
            if ($ended.Contains($split.Sheet)) { $problems.Add("line ${n}: a row of sheet $($split.Sheet) after its rows ended: $line"); continue }
            if ($null -ne $current) { $ended.Add($current) }
            $current = $split.Sheet; $lastRow = [int64]0; $lastCol = [int64]0
        }
        if ($pos.Row -lt $lastRow -or ($pos.Row -eq $lastRow -and $pos.Col -le $lastCol)) { $problems.Add("line ${n}: a cell out of document order on sheet $($split.Sheet): $line"); continue }
        $lastRow = $pos.Row; $lastCol = $pos.Col
    }
    return ,$problems
}

# `<impl> <args>` with the door's stderr set aside: its exit code and every
# line of its stdout.
function Invoke-Door([string]$impl, [string[]]$doorArgs) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $global:LASTEXITCODE = 0
        $lines = & $impl @doorArgs 2>$null
        $code = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $old
    }
    if ($null -eq $code) { $code = 0 }
    $text = if ($null -eq $lines) { '' } else { (@($lines) | ForEach-Object { [string]$_ }) -join "`n" }
    return @{ ExitCode = [int]$code; Text = $text }
}

# One implementation against one golden: a list of problems, empty when its
# difference is the golden whole.
function Measure-Impl([string]$impl, $g) {
    $problems = New-Object System.Collections.Generic.List[string]
    $golden = Join-Path $repoRoot $g.Golden
    $old = Join-Path $repoRoot $g.Old
    $new = Join-Path $repoRoot $g.New
    if (-not (Test-Path $old)) { $problems.Add("$($g.Name): no fixture at $old"); return ,$problems }
    if (-not (Test-Path $new)) { $problems.Add("$($g.Name): no fixture at $new"); return ,$problems }
    $r = Invoke-Door $impl @('diff', $old, $new)
    if ($r.ExitCode -eq 3) { $problems.Add("$($g.Name): diff not attempted (exit 3), but the golden exists"); return ,$problems }
    if ($r.ExitCode -ne 0) { $problems.Add("$($g.Name): diff exited $($r.ExitCode)"); return ,$problems }
    $want = Get-Lines ([System.IO.File]::ReadAllText($golden))
    $got = Get-Lines $r.Text
    $n = [Math]::Min($want.Count, $got.Count)
    for ($i = 0; $i -lt $n; $i++) {
        if ($want[$i] -ne $got[$i]) {
            $problems.Add("$($g.Name): differs at line $($i + 1) of $($want.Count): golden $($want[$i]) / door $($got[$i])")
            return ,$problems
        }
    }
    if ($want.Count -ne $got.Count) { $problems.Add("$($g.Name): the door printed $($got.Count) lines, the golden holds $($want.Count); they agree to line $n") }
    return ,$problems
}

# Every golden's floor and order: problems, and lines to print.
function Test-Goldens() {
    $problems = New-Object System.Collections.Generic.List[string]
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($g in $goldens) {
        $path = Join-Path $repoRoot $g.Golden
        if (-not (Test-Path $path)) { $problems.Add("$($g.Name): no golden at $path"); continue }
        $rows = Get-Lines ([System.IO.File]::ReadAllText($path))
        if ($rows.Count -lt $g.Floor) {
            $problems.Add("$($g.Name): the golden holds $($rows.Count) lines, below its floor of $($g.Floor)")
            $lines.Add("  $($g.Name): $($rows.Count) lines, BELOW THE FLOOR of $($g.Floor)  FAIL")
        } elseif ($rows.Count -gt $g.Floor) {
            $lines.Add("  $($g.Name): $($rows.Count) lines, above the floor of $($g.Floor) - raise the floor in this file")
        } else {
            $lines.Add("  $($g.Name): $($g.Floor) lines, at its floor")
        }
        $order = Test-Order $rows
        foreach ($p in $order) { $problems.Add("$($g.Name): $p"); $lines.Add("  $($g.Name): $p  FAIL") }
        if ($order.Count -eq 0) { $lines.Add("  $($g.Name): the fixed order holds (the sheets in one file alone, the names and Tables, then the cells sheet by sheet)") }
    }
    return @{ Problems = $problems; Lines = $lines }
}

if ($Control) {
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('frazaro_diff_golden_' + [System.IO.Path]::GetRandomFileName())
    New-Item -ItemType Directory -Path $tmp | Out-Null
    try {
        # Both fakes: the golden of the pair, found by the new file's base name.
        $map = ($goldens | ForEach-Object { "'" + [System.IO.Path]::GetFileNameWithoutExtension($_.New) + "' { '" + ((Join-Path $repoRoot $_.Golden) -replace "'", "''") + "' }" }) -join '; '
        $common = "param([Parameter(ValueFromRemainingArguments=`$true)][string[]]`$a)`n" +
                  "`$base = [System.IO.Path]::GetFileNameWithoutExtension(`$a[2])`n" +
                  "`$which = switch (`$base) { $map; default { exit 3 } }`n" +
                  "`$lines = [System.IO.File]::ReadAllText(`$which) -replace `"`r`n`", `"`n`" -split `"`n`"`n"
        $fake = Join-Path $tmp 'fake.ps1'
        [System.IO.File]::WriteAllText($fake, $common + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        # The mutant changes one value in the first changed row it prints.
        $mut = Join-Path $tmp 'mutant.ps1'
        $flip = "for (`$i = 0; `$i -lt `$lines.Count; `$i++) { if (`$lines[`$i] -like '(changed *') { `$lines[`$i] = `$lines[`$i] -replace '\)`$', 'X)'; break } }`n"
        [System.IO.File]::WriteAllText($mut, $common + $flip + "`$lines | ForEach-Object { Write-Output `$_ }`nexit 0`n")
        $fakeProblems = 0; $mutantProblems = 0; $named = $true
        foreach ($g in $goldens) {
            $r1 = Measure-Impl $fake $g
            $r2 = Measure-Impl $mut $g
            $fakeProblems += $r1.Count; $mutantProblems += $r2.Count
            $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $g.Golden)))
            $firstChanged = 0
            for ($i = 0; $i -lt $rows.Count; $i++) { if ($rows[$i] -like '(changed *') { $firstChanged = $i + 1; break } }
            if ($r2.Count -ne 1 -or -not ($r2[0] -like "*differs at line $firstChanged of*")) { $named = $false }
            Write-Output ("control, {0}: the fake has {1} problem(s); the mutant {2}: {3}" -f $g.Name, $r1.Count, $r2.Count, ($r2 -join '; '))
        }
        # The order pin: the third golden as it is, and a copy with its first
        # sheet-added row moved to the end.
        $rows = Get-Lines ([System.IO.File]::ReadAllText((Join-Path $repoRoot $goldens[2].Golden)))
        $r0 = Test-Order $rows
        $moved = New-Object System.Collections.Generic.List[string]
        $addedRow = @($rows | Where-Object { $_ -like '(sheet-added *' })[0]
        foreach ($l in $rows) { if ($l -ne $addedRow) { $moved.Add($l) } }
        $moved.Add($addedRow)
        $r3 = Test-Order $moved
        Write-Output ("control: the third golden's order {0} problem(s); the moved copy {1}: {2}" -f $r0.Count, $r3.Count, ($r3 -join '; '))
        if ($fakeProblems -eq 0 -and $named -and $mutantProblems -eq $goldens.Count -and $r0.Count -eq 0 -and $r3.Count -ge 1) {
            Write-Output 'OK: the check passes every golden, fails the mutant on each naming its line, and catches a row out of order'
            exit 0
        }
        Write-Output 'FAIL: the control did not behave as the header says'
        exit 1
    } finally {
        Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
    }
}

Write-Output '=== THE DIFF GOLDENS: REPRODUCED WHOLE, NEVER SHORTER, IN THE FIXED ORDER (PORT.8 slice 8c, oracle 9) ==='
$failed = New-Object System.Collections.Generic.List[string]
$tg = Test-Goldens
$tg.Lines | ForEach-Object { Write-Output $_ }
foreach ($p in $tg.Problems) { $failed.Add($p) }

if ($Impl -eq '') {
    foreach ($candidate in @('target/debug/frazaro.exe', 'target/release/frazaro.exe', 'target/debug/frazaro', 'target/release/frazaro')) {
        $p = Join-Path $repoRoot $candidate
        if (Test-Path $p) { $Impl = $p; break }
    }
}
if ($Impl -eq '' -or -not (Test-Path $Impl)) {
    Write-Output '  SKIPPED: no built door at target/debug/frazaro.exe or target/release/frazaro.exe (cargo build --workspace writes it; CI always has it)'
} else {
    foreach ($g in $goldens) {
        $r = Measure-Impl $Impl $g
        foreach ($p in $r) { $failed.Add($p); Write-Output "  $p  FAIL" }
        if ($r.Count -eq 0) { Write-Output "  $($g.Name): the door's difference is the golden, whole" }
    }
}

Write-Output ''
if ($failed.Count -eq 0) {
    Write-Output '=== CHECK: clean - every diff golden is reproduced whole, at or above its floor, in the fixed order ==='
    exit 0
}
Write-Output "=== CHECK: $($failed.Count) problem(s) ==="
$failed | ForEach-Object { Write-Output "  $_" }
exit 1
