<#
check_rule_coverage.ps1 - AS.1's own coverage report.

"Which rules have no test-success; which have only one" - BETA_ROADMAP.md's
AS.1, scoped over several passes once a static scan of the hand-written
scripts/english.vla turned out to undercount the moment a generator
(TABLE-FAMILY) is involved: a generator's own CALL site is one line in that
file; the rule/test it expands to don't exist as text anywhere a scanner
could read them. G-EXPANDER (this file's own real prerequisite) closes that
gap by writing the fully macro-expanded form to a sibling artifact,
scripts/english_expanded.vla - every english-vla/test-success/test-fail/
defmacro/english-function directive, generated or hand-written, in
registration order. This script reads that artifact, never english.vla
itself, for the identical reason check_backend_parity.ps1 reads
VLA_HeadTable.bas's own AddRow calls rather than re-deriving the form
catalog by hand: the artifact and the real grammar can never silently
drift apart, because the artifact IS the grammar, made literal.

WHAT COUNTS AS ATTRIBUTION: positional, not semantic - a heuristic, stated
as plainly as AS.8's own head-position scan states itself. Walking the
artifact top-to-bottom, a test-success is attributed to the nearest
PRECEDING english-vla/english-vla-override form. This is evidence a human
or generator INTENDED that test to prove that rule, never proof the test
actually FIRED it - a rule can be shadowed by an earlier, more general
rule's own wildcard slot (F.4's own found instance, "show cell in column
...") and still show a positionally-attached test here, because the wrong
rule firing can still produce byte-identical output to what the test
expects. F.4 stays the owner of that failure mode (general, not
corpus-bound, shadowing detection); this script reports density, not
correctness. test-fail is counted at the file level only, never attributed
to a rule - english.vla's own five test-fail proofs sit in one dedicated
negative-proofs block, none positionally adjacent to the rule they'd need
to be attributed to (checked directly against the real corpus).

FORM-BOUNDARY SCAN: a line matching ^\(([A-Za-z][\w-]*) opens a new
top-level form of that head symbol; everything through the line before the
next such match is its body. Column-0-anchored, multi-line-tolerant by
design - today's real artifact is always exactly one line per form
(VLA.VlaWriteForm), but this scanner makes no assumption either way, so it
needs no changes if G-EXPANDER's own pretty-printed rendering (VLA_Lint.
VlaLintFormat, GEXPANDERLINT.0) is what it actually reads, which is the
whole point: VLA_Lint.bas's own house style never indents a top-level form
relative to its siblings, only a form's OWN internal arguments verticalize
under it. A line matching ^;\s*row:\s*(.+)$ immediately above a form is
captured as that form's LISTOPS-PROVENANCE label when one exists.

Usage:  pwsh -File tools/check_rule_coverage.ps1 [-ArtifactPath <path>]
#>

param(
    [string]$ArtifactPath
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $ArtifactPath) {
    $ArtifactPath = Join-Path $repoRoot 'scripts\english_expanded.vla'
}

if (-not (Test-Path -LiteralPath $ArtifactPath)) {
    Write-Error "No expanded artifact at $ArtifactPath - export one first (Frazaro ribbon: Export Expanded Vocabulary), or pass -ArtifactPath."
}

$lines = Get-Content -LiteralPath $ArtifactPath

# --- Staleness gate: refuse loudly rather than report on stale input --------
# G-EXPANDER's own header (EnglishExpandedVocabularyText, VLA_English.bas):
#   line 1: "; GENERATED by ... from <bare-filename> - ..."
#   line 2: "; source-size: <N> bytes - ..."
if ($lines.Count -lt 2) {
    Write-Error "$ArtifactPath is too short to carry G-EXPANDER's own header - not a real expanded artifact."
}
$fromMatch = [regex]::Match($lines[0], 'from ([^\s]+\.vla)\b')
$sizeMatch = [regex]::Match($lines[1], 'source-size:\s*(\d+)\s*bytes')
if (-not $fromMatch.Success -or -not $sizeMatch.Success) {
    Write-Error "$ArtifactPath's own header doesn't match G-EXPANDER's stamped shape - re-export via Export Expanded Vocabulary rather than hand-editing this file."
}
$sourceName = $fromMatch.Groups[1].Value
$expectedSize = [long]$sizeMatch.Groups[1].Value
# The source may sit beside the artifact (the layout when G-EXPANDER was
# written) or under polyglotta (EDITION-MANIFEST moved every phrasebook
# there on 2026-09-01). Try both; the artifact header names only the file.
$artifactDir = Split-Path -Parent $ArtifactPath
$sourceCandidates = @((Join-Path $artifactDir $sourceName), (Join-Path (Join-Path $artifactDir 'polyglotta') $sourceName))
$sourcePath = $sourceCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
if (-not $sourcePath) {
    Write-Error "$ArtifactPath names its source as $sourceName, which is at neither $($sourceCandidates -join ' nor ') - can't verify freshness; re-export."
}
$actualSize = (Get-Item -LiteralPath $sourcePath).Length
if ($actualSize -ne $expectedSize) {
    Write-Error "$ArtifactPath is STALE: stamped source-size $expectedSize bytes, but $sourceName is $actualSize bytes now. Re-export via Export Expanded Vocabulary before trusting this report."
}

# --- Form-boundary scan ------------------------------------------------------
$formHeadRe = '^\(([A-Za-z][\w-]*)'
$rowTagRe   = '^;\s*row:\s*(.+)$'

class RuleEntry {
    [string]$Pattern
    [string]$RowTag
    [int]$TestCount
    [int]$Ordinal
}

$rules = New-Object System.Collections.Generic.List[RuleEntry]
$orphanTests = New-Object System.Collections.Generic.List[string]
$testFailCount = 0
$unknownForms = New-Object System.Collections.Generic.List[string]
$currentRule = $null
$pendingRowTag = ''
$ordinal = 0

foreach ($line in $lines) {
    $rowM = [regex]::Match($line, $rowTagRe)
    if ($rowM.Success) {
        $pendingRowTag = $rowM.Groups[1].Value
        continue
    }

    $headM = [regex]::Match($line, $formHeadRe)
    if (-not $headM.Success) {
        # header lines, blank lines, or a continuation line of a
        # multi-line (verticalized) form - never a new form boundary.
        continue
    }
    $head = $headM.Groups[1].Value
    $ordinal++

    switch -Regex ($head) {
        '^english-vla(-override)?$' {
            $patM = [regex]::Match($line, '^\(english-vla(?:-override)?\s+"((?:[^"\\]|\\.)*)"')
            $entry = [RuleEntry]::new()
            $entry.Pattern = if ($patM.Success) { $patM.Groups[1].Value } else { '(pattern unreadable)' }
            $entry.RowTag = $pendingRowTag
            $entry.TestCount = 0
            $entry.Ordinal = $ordinal
            $rules.Add($entry)
            $currentRule = $entry
        }
        '^test-success$' {
            if ($currentRule) {
                $currentRule.TestCount++
            } else {
                $sentM = [regex]::Match($line, '^\(test-success\s+"((?:[^"\\]|\\.)*)"')
                $orphanTests.Add($(if ($sentM.Success) { $sentM.Groups[1].Value } else { $line }))
            }
        }
        '^test-fail$' {
            $testFailCount++
        }
        '^(defmacro|english-function|keyword-alias)$' {
            # not owners - never reset currentRule (a defmacro helper can
            # sit before the rule it supports, e.g. set-formula ahead of
            # its own english-vla rule in the real corpus). keyword-alias
            # (LX5.1) is a language file's own control-flow vocabulary,
            # not a phrase rule - same non-owner treatment as defmacro.
        }
        default {
            $unknownForms.Add("line with head '$head': $line")
        }
    }
    $pendingRowTag = ''
}

# --- Report -------------------------------------------------------------
Write-Output '=== PROOF COVERAGE (test-success density over the expanded phrasebook) ==='
Write-Output "Artifact: $ArtifactPath"
Write-Output "Source verified fresh: $sourceName ($actualSize bytes)"
Write-Output "Rules scanned: $($rules.Count)"
Write-Output ''

$zero = $rules | Where-Object { $_.TestCount -eq 0 }
Write-Output "--- Zero tests, $($zero.Count) rule(s) ---"
$zero | ForEach-Object {
    $tag = if ($_.RowTag) { " [from $($_.RowTag)]" } else { '' }
    Write-Output "  $($_.Pattern)$tag"
}

Write-Output ''
$one = $rules | Where-Object { $_.TestCount -eq 1 }
Write-Output "--- Exactly one test, $($one.Count) rule(s) ---"
$one | ForEach-Object {
    $tag = if ($_.RowTag) { " [from $($_.RowTag)]" } else { '' }
    Write-Output "  $($_.Pattern)$tag"
}

Write-Output ''
$twoPlus = $rules | Where-Object { $_.TestCount -ge 2 }
Write-Output "--- test-fail proofs (file-level, never attributed to a rule): $testFailCount ---"

Write-Output ''
Write-Output "--- Orphan test-success (no preceding rule - should always be empty; non-empty means a bug in G-EXPANDER or this scanner, not the grammar): $($orphanTests.Count) ---"
$orphanTests | ForEach-Object { Write-Output "  $_" }

if ($unknownForms.Count -gt 0) {
    Write-Output ''
    Write-Output "--- Unrecognized top-level forms, $($unknownForms.Count) (not one of the six known directives - investigate) ---"
    $unknownForms | ForEach-Object { Write-Output "  $_" }
}

Write-Output ''
Write-Output "=== SUMMARY: $($twoPlus.Count)/$($rules.Count) rules have 2+ tests; $($one.Count) have exactly one; $($zero.Count) have zero ==="
