<#
export_headtable.ps1 - the head table, exported to data (PORT.5, slice 5c).

WHY: src/VLA_HeadTable.bas is the catalogue of the core forms, one row per
head symbol: its aliases, arity, interpreter and VBA routines, its standing
in the formula dialect, and whether it is export-only. The core (core/)
reads the same catalogue as data, never typed in twice: this script writes
vla-lang/data/headtable.vla (the language's crate since PORT.12), one form per row,

    (head <symbol> (<alias> ...) "<arity>" "<interpreter routine>"
          "<VBA routine>" <yes|refused|undeclared> <true|false>)

in the order BuildRows adds them. The VBA stays the source; this export is
re-run when the table changes, and tools/check_data_exports.ps1 fails when
the two have drifted (check_devrig_mods_parity's shape: two lists that must
agree, held together mechanically).

WHAT IT READS: every `AddRow rows, "<symbol>", "<aliases>", "<arity>",
"<interp>", "<vba>", "<formula>", True|False` line of BuildRows. The alias
column is split on commas and trimmed, as VlaHeadTableAliasMap splits it.

House style: PowerShell 5.1, host-free, no Excel, no COM, no network.

Usage:  powershell -File tools\export_headtable.ps1          (writes vla-lang\data\headtable.vla)
        powershell -File tools\export_headtable.ps1 -Print   (writes the text to stdout)
#>
param([switch]$Print)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$srcPath  = Join-Path $repoRoot 'src/VLA_HeadTable.bas'
$outPath  = Join-Path $repoRoot 'vla-lang/data/headtable.vla'

$all = Get-Content -LiteralPath $srcPath
$start = -1; $end = -1
for ($i = 0; $i -lt $all.Count; $i++) {
    if ($start -lt 0 -and $all[$i] -match '^Private Function BuildRows\(') { $start = $i; continue }
    if ($start -ge 0 -and $all[$i] -match '^End Function') { $end = $i; break }
}
if ($start -lt 0 -or $end -lt 0) { throw "BuildRows not found in $srcPath - has its shape changed?" }

function ConvertTo-VlaString([string]$s) {
    return '"' + ($s -replace '\\', '\\' -replace '"', '\"') + '"'
}

$rowRe = '^\s*AddRow rows, "([^"]*)", "([^"]*)", "([^"]*)", "([^"]*)", "([^"]*)", "([^"]*)", (True|False)\s*$'
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('; GENERATED by tools/export_headtable.ps1 from src/VLA_HeadTable.bas - do not hand-edit or lint; the VBA is the source (PORT.5).')
$lines.Add('; (head <symbol> (<alias> ...) "<arity>" "<interpreter routine>" "<VBA routine>" <yes|refused|undeclared> <export-only>), in the order BuildRows adds them.')
$count = 0
for ($i = $start + 1; $i -lt $end; $i++) {
    $line = $all[$i]
    if ($line -notmatch '^\s*AddRow rows,') { continue }
    if ($line -notmatch $rowRe) { throw "an AddRow line this script cannot read (a quote in a column?): $line" }
    $symbol = $Matches[1]
    if ($symbol -match '[\s();"]' -or $symbol.Length -eq 0) { throw "a symbol that is not one token: '$symbol'" }
    $aliases = @($Matches[2] -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_.Length -gt 0 })
    foreach ($a in $aliases) { if ($a -match '[\s();"]') { throw "an alias that is not one token: '$a'" } }
    $formula = $Matches[6]
    if ($formula -notin @('yes', 'refused', 'undeclared')) { throw "a formula column that is not yes, refused or undeclared: '$formula' on $symbol" }
    $exportOnly = if ($Matches[7] -eq 'True') { 'true' } else { 'false' }
    $lines.Add(('(head {0} ({1}) {2} {3} {4} {5} {6})' -f $symbol, ($aliases -join ' '),
        (ConvertTo-VlaString $Matches[3]), (ConvertTo-VlaString $Matches[4]), (ConvertTo-VlaString $Matches[5]),
        $formula, $exportOnly))
    $count++
}
if ($count -eq 0) { throw "no AddRow line matched - the table's shape has changed; update this script" }

$text = ($lines -join "`r`n") + "`r`n"
if ($Print) {
    # Through the pipeline, so a caller can capture it (check_data_exports.ps1 does).
    Write-Output $text
} else {
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($outPath, $text, $utf8)
    Write-Host "wrote $count rows -> $outPath"
}
