# optimize0_lp.ps1 - export an OPTIMIZE.0 fixture as a clingo program.
#
# DEV-ONLY ORACLE (settled 2026-09-19, the owner's call): clingo, the Potassco
# answer-set solver (MIT), checks OPTIMIZE's answers at sizes where hand-checking
# cannot. This script only WRITES a .lp text file. It never runs clingo, nothing
# in Frazaro calls it, no clingo binary is kept in this repository, and SD-13
# is untouched: the owner installs clingo separately and runs it by hand.
#
# The fixture is the same closed-form definition as tools/VLA_DiagO0.bas
# (O0Fixture) and tools/optimize0_expected.ps1: people i = 1..P, Senior when
# i mod 4 = 0, Contract 4 (odd) or 5 (even); shifts s = 1..21W, day
# (s-1)\3+1, Night when (s-1) mod 3 = 2; leave when (i + day) mod 7 = 0; need
# max(1, P\5) (tight, the reference) or Early 2, Late 3, Night 4 (-Loose); the
# kept schedule a round-robin in Id order.
#
# COMPARE ONLY TWO THINGS with OPTIMIZE's answers: whether a schedule exists
# (SATISFIABLE / UNSATISFIABLE), and the OPTIMAL COST (clingo's
# "Optimization:" line - overtime first, then changes from the kept schedule).
# Never the schedule itself: OPTIMIZE breaks ties by the Tables' row order, and
# clingo promises no particular one of several equally good schedules.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\optimize0_lp.ps1 -People 10 -Weeks 1
#   ... -Loose                   the loose needs instead of the tight ones
#   ... -Toy                     the toy: count its valid worlds (expect 7,290)
#   ... -KeptFirst               add a value-order hint (try the kept choice first);
#                                clingo must then be run with --heuristic=Domain.
#                                The hint changes how fast, never which costs are optimal.
#   ... -OutDir C:\somewhere     default: $env:TEMP
#
# then, by hand:   clingo <file>.lp            (a fixture: the optimum)
#                  clingo <file>.lp 0          (the toy: every model, counted)

param(
    [int]$People = 10,
    [int]$Weeks = 1,
    [switch]$Loose,
    [switch]$Toy,
    [switch]$KeptFirst,
    [string]$OutDir = $env:TEMP
)

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'

function Get-ShiftDay([int]$shiftNo) { [int][math]::Floor(($shiftNo - 1) / 3) + 1 }
function Get-ShiftSlot([int]$shiftNo) { ($shiftNo - 1) % 3 }
function Get-ShiftWeek([int]$shiftNo) { [int][math]::Floor(((Get-ShiftDay $shiftNo) - 1) / 7) + 1 }
function Test-OnLeave([int]$person, [int]$dayNo) { (($person + $dayNo) % 7) -eq 0 }
function Get-TightNeed([int]$nPeople) { $t = [int][math]::Floor($nPeople / 5); if ($t -lt 1) { 1 } else { $t } }
function Get-Need([int]$shiftNo) {
    if ($Loose) { 2 + (Get-ShiftSlot $shiftNo) } else { Get-TightNeed $People }
}

$text = New-Object System.Text.StringBuilder

if ($Toy) {
    $file = Join-Path $OutDir 'optimize0_toy.lp'
    [void]$text.AppendLine('% OPTIMIZE.0 toy: 5 people, 7 shifts, exactly 2 per shift, never two in a row.')
    [void]$text.AppendLine('% Run:  clingo optimize0_toy.lp 0     Expect:  Models : 7290  (10 x 3^6, by hand)')
    [void]$text.AppendLine('person(1..5).')
    [void]$text.AppendLine('shift(1..7).')
    [void]$text.AppendLine('next(S,S+1) :- shift(S), shift(S+1).')
    [void]$text.AppendLine('2 { assign(S,P) : person(P) } 2 :- shift(S).')
    [void]$text.AppendLine(':- assign(S,P), assign(T,P), next(S,T).')
    [void]$text.AppendLine('#show assign/2.')
} else {
    if ($People -lt 1 -or $Weeks -lt 1) { throw 'People and Weeks must both be at least 1.' }
    $name = "optimize0_$People" + 'x' + "$Weeks" + $(if ($Loose) { 'L' } else { '' })
    $file = Join-Path $OutDir "$name.lp"
    $nS = 21 * $Weeks
    [void]$text.AppendLine("% OPTIMIZE.0 fixture $name - generated by tools/optimize0_lp.ps1; do not edit by hand.")
    [void]$text.AppendLine("% Run:  clingo $name.lp     Record: SATISFIABLE or UNSATISFIABLE, and the Optimization line.")
    [void]$text.AppendLine('')
    [void]$text.AppendLine('% --- facts ---')
    for ($ip = 1; $ip -le $People; $ip++) {
        $contract = if (($ip % 2) -eq 1) { 4 } else { 5 }
        [void]$text.AppendLine("person($ip). contract($ip,$contract).")
        if (($ip % 4) -eq 0) { [void]$text.AppendLine("senior($ip).") }
        for ($id = 1; $id -le 7 * $Weeks; $id++) { if (Test-OnLeave $ip $id) { [void]$text.AppendLine("leave($ip,$id).") } }
    }
    for ($iw = 1; $iw -le $Weeks; $iw++) { [void]$text.AppendLine("week($iw).") }
    $cursor = 0
    for ($is = 1; $is -le $nS; $is++) {
        $need = Get-Need $is
        [void]$text.AppendLine("shift($is). day_of($is,$(Get-ShiftDay $is)). week_of($is,$(Get-ShiftWeek $is)). need($is,$need).")
        if ((Get-ShiftSlot $is) -eq 2) { [void]$text.AppendLine("night($is).") }
        if ($is -lt $nS) { [void]$text.AppendLine("next($is,$($is + 1)).") }
        for ($j = 0; $j -lt $need; $j++) {
            $keptPerson = (($cursor + $j) % $People) + 1
            [void]$text.AppendLine("kept($is,$keptPerson).")
        }
        $cursor += $need
    }
    [void]$text.AppendLine('')
    [void]$text.AppendLine('% --- the rules: the reference roster ---')
    [void]$text.AppendLine('% the pool: anyone, any shift, except on a leave day')
    [void]$text.AppendLine('elig(S,P) :- shift(S), person(P), day_of(S,D), not leave(P,D).')
    [void]$text.AppendLine('% the choice: exactly need(S) people on every shift')
    [void]$text.AppendLine('N { assign(S,P) : elig(S,P) } N :- shift(S), need(S,N).')
    [void]$text.AppendLine('% never two shifts in a row')
    [void]$text.AppendLine(':- assign(S,P), assign(T,P), next(S,T).')
    [void]$text.AppendLine('% at most 5 shifts a week - a direct cardinality constraint, which propagates as a bound')
    [void]$text.AppendLine(':- person(P), week(W), #count { S : assign(S,P), week_of(S,W) } > 5.')
    [void]$text.AppendLine('% shifts worked per person-week, read only by the objective below')
    [void]$text.AppendLine('works(P,W,N) :- person(P), week(W), N = #count { S : assign(S,P), week_of(S,W) }.')
    [void]$text.AppendLine('% a senior on every night')
    [void]$text.AppendLine(':- night(S), #count { P : assign(S,P), senior(P) } = 0.')
    [void]$text.AppendLine('% the objective, in OPTIMIZE''s order: overtime first, then changes from the kept schedule')
    [void]$text.AppendLine('over(P,W,N-C) :- works(P,W,N), contract(P,C), N > C.')
    [void]$text.AppendLine('#minimize { O@2,P,W : over(P,W,O) }.')
    [void]$text.AppendLine('#minimize { 1@1,S,P : assign(S,P), not kept(S,P) ; 1@1,S,P : kept(S,P), not assign(S,P) }.')
    if ($KeptFirst) {
        # OPTIMIZE.7's value order: try the kept schedule's own choice first.
        # Only takes effect with clingo --heuristic=Domain.
        [void]$text.AppendLine('% value order (-KeptFirst): try the kept schedule''s choice first; run with --heuristic=Domain')
        [void]$text.AppendLine('#heuristic assign(S,P) : kept(S,P). [1,true]')
    }
    [void]$text.AppendLine('#show assign/2.')
}

if (-not (Test-Path $OutDir)) { throw "no folder $OutDir" }
[System.IO.File]::WriteAllText($file, $text.ToString(), (New-Object System.Text.ASCIIEncoding))
Write-Output "wrote $file"
