<#
ter567_fixture.ps1 - live-test fixtures for TER-5, TER-6 and TER-7.

-Make builds one folder per test under -Root (default C:\TER567), each
holding only that test's own program files. -Check reads the disk back and
prints PASS/FAIL for everything a FILE can show: the GENERATED stamps, the
encoding of a translated .vla (UTF-8) beside a translated .vba (ANSI), and
- through git - that regenerating instructions.vla and the goldens added the
stamp line and changed nothing else. What a dialog SAYS is read by the
person at the keyboard; this script only checks what reached the disk.

Usage:
  powershell -ExecutionPolicy Bypass -File tools\ter567_fixture.ps1 -Make
  (run the numbered steps in Excel)
  powershell -ExecutionPolicy Bypass -File tools\ter567_fixture.ps1 -Check

-Make deletes -Root first, but only a folder this script made (it carries
ter567.marker). Not wired into any check or test run - a live-test aid,
like u20_lint_fixture.ps1.

Non-ASCII fixture text is built from [char] codes so this file stays ASCII.
#>
param([switch]$Make, [switch]$Check, [string]$Root = 'C:\TER567')
$ErrorActionPreference = 'Stop'

$repo       = Split-Path -Parent $PSScriptRoot
$utf8       = New-Object System.Text.UTF8Encoding($false)
$utf8Strict = New-Object System.Text.UTF8Encoding($false, $true)
$CRLF       = "`r`n"
$eAcute     = [string][char]0x00E9

function Write-Text([string]$path, [string]$text) {
    [System.IO.File]::WriteAllBytes($path, $utf8.GetBytes($text))
}
function Say([string]$name, [bool]$ok, [string]$detail) {
    if ($ok) { Write-Output "PASS  $name" } else { Write-Output "FAIL  $name - $detail" }
}
function Contains-Bytes([byte[]]$hay, [byte[]]$needle) {
    for ($i = 0; $i -le $hay.Length - $needle.Length; $i++) {
        $hit = $true
        for ($j = 0; $j -lt $needle.Length; $j++) {
            if ($hay[$i + $j] -ne $needle[$j]) { $hit = $false; break }
        }
        if ($hit) { return $true }
    }
    return $false
}
function First-Line([string]$path) {
    $b = [System.IO.File]::ReadAllBytes($path)
    $text = $utf8.GetString($b)
    $nl = $text.IndexOf("`n")
    if ($nl -lt 0) { return $text.TrimEnd("`r") }
    return $text.Substring(0, $nl).TrimEnd("`r")
}
# "added removed" for one tracked file, from git's own normalized diff.
function Diff-Stat([string]$rel) {
    $line = & git -C $repo diff --numstat -- $rel 2>$null
    if (-not $line) { return '0 0' }
    $parts = ([string]$line).Split("`t")
    return ($parts[0] + ' ' + $parts[1])
}

if ($Make) {
    if (Test-Path -LiteralPath $Root) {
        if (-not (Test-Path -LiteralPath (Join-Path $Root 'ter567.marker'))) {
            throw "$Root exists and was not made by this script (no ter567.marker) - pick another -Root."
        }
        Remove-Item -LiteralPath $Root -Recurse -Force
    }
    foreach ($d in 't6', 't7') {
        New-Item -ItemType Directory -Force -Path (Join-Path $Root $d) | Out-Null
    }
    Write-Text (Join-Path $Root 'ter567.marker') 'made by tools\ter567_fixture.ps1'
    Write-Text (Join-Path $Root 't6\cafe.txt') ("Put `"caf$eAcute`" into cell A1." + $CRLF)
    Write-Text (Join-Path $Root 't7\comments.txt') ('# only a note' + $CRLF + '# and another note' + $CRLF)
    [System.IO.File]::WriteAllBytes((Join-Path $Root 't7\empty.txt'), [byte[]]@())
    Write-Output "Made $Root - now run the Excel steps, then -Check."
    exit 0
}

if (-not $Check) { throw 'Pass -Make or -Check.' }

# --- TER-5: the two regenerated files in the repo ---
$ivla = Join-Path $repo 'scripts\instructions.vla'
Say 'TER-5: instructions.vla starts with the Translate to VLA stamp' `
    ((First-Line $ivla).StartsWith('; GENERATED by Translate to VLA from instructions.txt')) ("line 1: " + (First-Line $ivla))
Say 'TER-5: instructions.vla changed by exactly one added line (the stamp)' `
    ((Diff-Stat 'scripts/instructions.vla') -eq '1 0') ("git numstat added/removed: " + (Diff-Stat 'scripts/instructions.vla'))

$gvla = Join-Path $repo 'scripts\instructions_golden.vla'
Say 'TER-5: instructions_golden.vla starts with the VlaWriteGoldens stamp' `
    ((First-Line $gvla).StartsWith('; GENERATED by VlaWriteGoldens from instructions.txt')) ("line 1: " + (First-Line $gvla))
Say 'TER-5: instructions_golden.vla changed by exactly one added line (the stamp)' `
    ((Diff-Stat 'scripts/instructions_golden.vla') -eq '1 0') ("git numstat added/removed: " + (Diff-Stat 'scripts/instructions_golden.vla'))
Say 'TER-5: instructions_golden.vba is unchanged' `
    ((Diff-Stat 'scripts/instructions_golden.vba') -eq '0 0') ("git numstat added/removed: " + (Diff-Stat 'scripts/instructions_golden.vba'))

# --- TER-6: one sentence with an e-acute, translated both ways ---
$cvla = Join-Path $Root 't6\cafe.vla'
$cvba = Join-Path $Root 't6\cafe.vba'
if (-not (Test-Path -LiteralPath $cvla)) {
    Say 'TER-6: cafe.vla' $false "$cvla does not exist - was Translate to VLA saved there?"
} else {
    $b = [System.IO.File]::ReadAllBytes($cvla)
    $strictOk = $true
    try { $null = $utf8Strict.GetString($b) } catch { $strictOk = $false }
    Say 'TER-6: cafe.vla is strict UTF-8' $strictOk 'not valid UTF-8'
    Say 'TER-6: cafe.vla keeps the e-acute as UTF-8 (C3 A9)' (Contains-Bytes $b ([byte[]](0x63, 0x61, 0x66, 0xC3, 0xA9))) 'no "caf" + C3 A9 in the file'
    Say 'TER-6: cafe.vla starts with the stamp naming cafe.txt' `
        ((First-Line $cvla).StartsWith('; GENERATED by Translate to VLA from cafe.txt')) ("line 1: " + (First-Line $cvla))
}
if (-not (Test-Path -LiteralPath $cvba)) {
    Say 'TER-6: cafe.vba' $false "$cvba does not exist - was Translate to VBA saved there?"
} else {
    $b = [System.IO.File]::ReadAllBytes($cvba)
    Say 'TER-6: cafe.vba keeps the e-acute in the system code page (E9), not UTF-8' `
        ((Contains-Bytes $b ([byte[]](0x63, 0x61, 0x66, 0xE9))) -and -not (Contains-Bytes $b ([byte[]](0xC3, 0xA9)))) 'expected "caf" + E9 and no C3 A9'
}

# --- TER-7: programs with no sentences translate ---
foreach ($name in 'comments', 'empty') {
    $p = Join-Path $Root "t7\$name.vla"
    if (-not (Test-Path -LiteralPath $p)) {
        Say "TER-7: $name.vla" $false "$p does not exist - did Translate to VLA fail?"
    } else {
        Say "TER-7: $name.vla was written, stamped from $name.txt" `
            ((First-Line $p).StartsWith("; GENERATED by Translate to VLA from $name.txt")) ("line 1: " + (First-Line $p))
    }
}
